/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t r_typesheet7_t3x[];
extern const uint8_t r_typesheet7_t3x_end[];
#if __cplusplus >= 201103L
static constexpr size_t r_typesheet7_t3x_size=6681;
#else
static const size_t r_typesheet7_t3x_size=6681;
#endif
