R-TYPE: RTypeServer::Server Class Reference
RTypeServer::Server Class Reference
#include <Server.hpp>
Public Member Functions
Server ()
~Server ()
void loadEngineLib ()
void startServer (Engine::NetworkManager::Role role, const std::string &ip, uint16_t port, int player_nb)
void initEngine ()
void gameLoop ()
void createPlayer ()
void createPlayerProjectile (float x, float y)
void createEnemy (float x, float y, ENEMY_TYPES enemy_type)
void createBackground ()
Private Attributes
std::shared_ptr< Engine::NetworkManager >(* createNetworkManagerFunc)(Engine::NetworkManager::Role, const std::string &, uint16_t)
std::shared_ptr< Engine::Mediator >(* createMediatorFunc)()
std::shared_ptr< Engine::NetworkManager > networkManager
std::shared_ptr< Engine::Mediator > mediator
std::shared_ptr< Engine::Systems::PhysicsNoEngineSystem > physics_system {}
std::shared_ptr< Engine::Systems::PlayerControl > player_control_system {}
std::shared_ptr< Engine::Systems::Collision > collision_system {}
std::shared_ptr< Engine::Systems::EnemySystem > enemy_system {}
int player_nb = 4
Detailed Description
Definition at line 21 of file Server.hpp.
Constructor & Destructor Documentation
Server()
RTypeServer::Server::Server ()
Definition at line 26 of file Server.cpp.
~Server()
RTypeServer::Server::~Server ()
Definition at line 310 of file Server.cpp.
Member Function Documentation
createBackground()
void RTypeServer::Server::createBackground ()
Definition at line 283 of file Server.cpp.
createEnemy()
void RTypeServer::Server::createEnemy (float x, float y, ENEMY_TYPES enemy_type)
Definition at line 248 of file Server.cpp.
References ENEMY.
createPlayer()
void RTypeServer::Server::createPlayer ()
Definition at line 169 of file Server.cpp.
References Engine::Components::Sprite_s::frame_nb, and Engine::Components::Sprite_s::sprite_name.
createPlayerProjectile()
void RTypeServer::Server::createPlayerProjectile (float x, float y)
Definition at line 212 of file Server.cpp.
References PLAYER_PROJECTILE.
gameLoop()
void RTypeServer::Server::gameLoop ()
Definition at line 111 of file Server.cpp.
References SIMPLE.
Referenced by main().
initEngine()
void RTypeServer::Server::initEngine ()
Definition at line 49 of file Server.cpp.
References Engine::Systems::EnemySystem::init(), and Engine::Systems::PlayerControl::init().
Referenced by main().
loadEngineLib()
void RTypeServer::Server::loadEngineLib ()
Definition at line 30 of file Server.cpp.
References Engine::DLLoader::getFunction().
Referenced by main().
startServer()
void RTypeServer::Server::startServer (Engine::NetworkManager::Role role, const std::string & ip, uint16_t port, int player_nb)
Definition at line 43 of file Server.cpp.
Referenced by main().
Member Data Documentation
collision_system
std::shared_ptr<Engine::Systems::Collision> RTypeServer::Server::collision_system {} private
Definition at line 43 of file Server.hpp.
createMediatorFunc
std::shared_ptr< Engine::Mediator >(* RTypeServer::Server::createMediatorFunc) () private
Definition at line 34 of file Server.hpp.
createNetworkManagerFunc
std::shared_ptr< Engine::NetworkManager >(* RTypeServer::Server::createNetworkManagerFunc) (Engine::NetworkManager::Role, const std::string &, uint16_t) private
Definition at line 34 of file Server.hpp.
enemy_system
std::shared_ptr<Engine::Systems::EnemySystem> RTypeServer::Server::enemy_system {} private
Definition at line 44 of file Server.hpp.
mediator
std::shared_ptr<Engine::Mediator> RTypeServer::Server::mediator private
Definition at line 39 of file Server.hpp.
networkManager
std::shared_ptr<Engine::NetworkManager> RTypeServer::Server::networkManager private
Definition at line 38 of file Server.hpp.
physics_system
std::shared_ptr<Engine::Systems::PhysicsNoEngineSystem> RTypeServer::Server::physics_system {} private
Definition at line 41 of file Server.hpp.
player_control_system
std::shared_ptr<Engine::Systems::PlayerControl> RTypeServer::Server::player_control_system {} private
Definition at line 42 of file Server.hpp.
player_nb
int RTypeServer::Server::player_nb = 4 private
Definition at line 46 of file Server.hpp.
The documentation for this class was generated from the following files:
Server.hpp
Server.cpp