R-TYPE: Launch Class Reference
Launch Class Reference
#include <Launch.hpp>
Public Member Functions
Launch (sf::Vector2u windowSize)
~Launch ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (sf::Vector2u newSize)
Private Member Functions
void centerLogo ()
Private Attributes
sf::Texture logoTexture
sf::Sprite logoSprite
sf::Vector2u windowSize
Detailed Description
Definition at line 14 of file Launch.hpp.
Constructor & Destructor Documentation
Launch()
Launch::Launch (sf::Vector2u windowSize)
Definition at line 11 of file Launch.cpp.
~Launch()
Launch::~Launch () default
Member Function Documentation
centerLogo()
void Launch::centerLogo () private
Definition at line 27 of file Launch.cpp.
References logoSprite, and windowSize.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void Launch::draw (sf::RenderWindow & window)
Definition at line 37 of file Launch.cpp.
References logoSprite.
Referenced by GameManager::render().
handleEvent()
void Launch::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 42 of file Launch.cpp.
References centerLogo(), and windowSize.
Referenced by GameManager::handleEvents().
loadResources()
bool Launch::loadResources ()
Definition at line 15 of file Launch.cpp.
References centerLogo(), logoSprite, and logoTexture.
Referenced by GameManager::GameManager().
update()
void Launch::update ()
Definition at line 57 of file Launch.cpp.
Referenced by GameManager::update().
updateWindowSize()
void Launch::updateWindowSize (sf::Vector2u newSize)
Definition at line 61 of file Launch.cpp.
References centerLogo(), and windowSize.
Referenced by GameManager::handleWindowResize().
Member Data Documentation
logoSprite
sf::Sprite Launch::logoSprite private
Definition at line 26 of file Launch.hpp.
Referenced by centerLogo(), draw(), and loadResources().
logoTexture
sf::Texture Launch::logoTexture private
Definition at line 25 of file Launch.hpp.
Referenced by loadResources().
windowSize
sf::Vector2u Launch::windowSize private
Definition at line 27 of file Launch.hpp.
Referenced by centerLogo(), handleEvent(), and updateWindowSize().
The documentation for this class was generated from the following files:
Launch.hpp
Launch.cpp