R-TYPE: Engine::EventManager Class Reference
Engine::EventManager Class Reference
#include <EventManager.hpp>
Public Member Functions
void addListener (EventId event_id, std::function< void(Event &)> const &listener)
void sendEvent (Event &event)
void sendEvent (EventId event_id)
Private Attributes
std::unordered_map< EventId, std::list< std::function< void(Event &)> > > listeners
Detailed Description
Definition at line 16 of file EventManager.hpp.
Member Function Documentation
addListener()
void Engine::EventManager::addListener (EventId event_id, std::function< void(Event &)> const & listener) inline
Definition at line 18 of file EventManager.hpp.
References listeners.
sendEvent() [1/2]
void Engine::EventManager::sendEvent (Event & event) inline
Definition at line 22 of file EventManager.hpp.
References listeners.
sendEvent() [2/2]
void Engine::EventManager::sendEvent (EventId event_id) inline
Definition at line 30 of file EventManager.hpp.
References listeners.
Member Data Documentation
listeners
std::unordered_map<EventId, std::list<std::function<void(Event &)> > > Engine::EventManager::listeners private
Definition at line 39 of file EventManager.hpp.
Referenced by addListener(), sendEvent(), and sendEvent().
The documentation for this class was generated from the following file:
EventManager.hpp