R-TYPE: Button Class Reference
Button Class Reference
#include <Button.hpp>
Public Member Functions
Button ()=default
Button (sf::Vector2f position, sf::Vector2f size, const std::string &text, sf::Font &font)
~Button ()=default
void draw (sf::RenderWindow &window)
bool isClicked (Engine::Utils::Vec2Int mousePos)
void setHovered (bool hovered)
void updatePosition (sf::Vector2f newPosition)
void updateSize (sf::Vector2f newSize)
void updatePositionAndSize (sf::Vector2f newPosition, sf::Vector2f newSize)
void setCharacterSize (int size)
Private Attributes
sf::RectangleShape shape
sf::Text label
Detailed Description
Definition at line 16 of file Button.hpp.
Constructor & Destructor Documentation
Button() [1/2]
Button::Button () default
Button() [2/2]
Button::Button (sf::Vector2f position, sf::Vector2f size, const std::string & text, sf::Font & font)
Definition at line 10 of file Button.cpp.
References label, and shape.
~Button()
Button::~Button () default
Member Function Documentation
draw()
void Button::draw (sf::RenderWindow & window)
Definition at line 30 of file Button.cpp.
References label, and shape.
Referenced by GameManager::render().
isClicked()
bool Button::isClicked (Engine::Utils::Vec2Int mousePos)
Definition at line 36 of file Button.cpp.
References shape, Engine::Utils::Vec2Int::x, and Engine::Utils::Vec2Int::y.
Referenced by GameManager::handleMouseClick(), and GameManager::handleMouseMove().
setCharacterSize()
void Button::setCharacterSize (int size) inline
Definition at line 30 of file Button.hpp.
References label, and shape.
Referenced by GameManager::GameManager().
setHovered()
void Button::setHovered (bool hovered)
Definition at line 41 of file Button.cpp.
References shape.
Referenced by GameManager::handleEvents(), and GameManager::handleMouseMove().
updatePosition()
void Button::updatePosition (sf::Vector2f newPosition)
Definition at line 50 of file Button.cpp.
References label, and shape.
updatePositionAndSize()
void Button::updatePositionAndSize (sf::Vector2f newPosition, sf::Vector2f newSize)
Definition at line 73 of file Button.cpp.
References label, and shape.
Referenced by GameManager::handleWindowResize(), and GameManager::updatePositions().
updateSize()
void Button::updateSize (sf::Vector2f newSize)
Definition at line 61 of file Button.cpp.
References label, and shape.
Member Data Documentation
label
sf::Text Button::label private
Definition at line 43 of file Button.hpp.
Referenced by Button(), draw(), setCharacterSize(), updatePosition(), updatePositionAndSize(), and updateSize().
shape
sf::RectangleShape Button::shape private
Definition at line 42 of file Button.hpp.
Referenced by Button(), draw(), isClicked(), setCharacterSize(), setHovered(), updatePosition(), updatePositionAndSize(), and updateSize().
The documentation for this class was generated from the following files:
Button.hpp
Button.cpp