R-TYPE: RtypeServer::Protocol Class Reference
RtypeServer::Protocol Class Reference
#include <Protocol.hpp>
Public Member Functions
Protocol ()
~Protocol ()
void writeHeader (std::vector< uint8_t > &out, const NetHeader &h)
NetHeader readHeader (const uint8_t *data, std::size_t size)
void append_u8 (std::vector< uint8_t > &out, uint8_t v)
void append_u16be (std::vector< uint8_t > &out, uint16_t v)
void append_u32be (std::vector< uint8_t > &out, uint32_t v)
void append_i16be (std::vector< uint8_t > &out, int16_t v)
uint8_t read_u8 (const uint8_t *data, std::size_t &off, std::size_t size)
uint16_t read_u16be (const uint8_t *data, std::size_t &off, std::size_t size)
uint32_t read_u32be (const uint8_t *data, std::size_t &off, std::size_t size)
int16_t read_i16be (const uint8_t *data, std::size_t &off, std::size_t size)
void writeHelloBody (std::vector< uint8_t > &out, const HelloBody &b)
HelloBody readHelloBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeWelcomeBody (std::vector< uint8_t > &out, const WelcomeBody &b)
WelcomeBody readWelcomeBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeCreateRoomBody (std::vector< uint8_t > &out, const CreateRoomBody &b)
CreateRoomBody readCreateRoomBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeJoinRoomBody (std::vector< uint8_t > &out, const JoinRoomBody &b)
JoinRoomBody readJoinRoomBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeMessageBody (std::vector< uint8_t > &out, const MessageBody &b)
MessageBody readMessageBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomCreatedBody (std::vector< uint8_t > &out, const RoomCreatedBody &b)
RoomCreatedBody readRoomCreatedBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomJoinedBody (std::vector< uint8_t > &out, const RoomJoinedBody &b)
RoomJoinedBody readRoomJoinedBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomLeftBody (std::vector< uint8_t > &out, const RoomLeftBody &b)
RoomLeftBody readRoomLeftBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomListBody (std::vector< uint8_t > &out, const RoomListBody &b)
RoomListBody readRoomListBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomMessageBody (std::vector< uint8_t > &out, const RoomMessageBody &b)
RoomMessageBody readRoomMessageBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomErrorBody (std::vector< uint8_t > &out, const RoomErrorBody &b)
RoomErrorBody readRoomErrorBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeString (std::vector< uint8_t > &out, const std::string &str)
std::string readString (const uint8_t *data, std::size_t size, std::size_t &off)
Protocol ()
~Protocol ()
void writeHeader (std::vector< uint8_t > &out, const NetHeader &h)
NetHeader readHeader (const uint8_t *data, std::size_t size)
void append_u8 (std::vector< uint8_t > &out, uint8_t v)
void append_u16be (std::vector< uint8_t > &out, uint16_t v)
void append_u32be (std::vector< uint8_t > &out, uint32_t v)
void append_i16be (std::vector< uint8_t > &out, int16_t v)
uint8_t read_u8 (const uint8_t *data, std::size_t &off, std::size_t size)
uint16_t read_u16be (const uint8_t *data, std::size_t &off, std::size_t size)
uint32_t read_u32be (const uint8_t *data, std::size_t &off, std::size_t size)
int16_t read_i16be (const uint8_t *data, std::size_t &off, std::size_t size)
void writeHelloBody (std::vector< uint8_t > &out, const HelloBody &b)
HelloBody readHelloBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeWelcomeBody (std::vector< uint8_t > &out, const WelcomeBody &b)
WelcomeBody readWelcomeBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeCreateRoomBody (std::vector< uint8_t > &out, const CreateRoomBody &b)
CreateRoomBody readCreateRoomBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeJoinRoomBody (std::vector< uint8_t > &out, const JoinRoomBody &b)
JoinRoomBody readJoinRoomBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeMessageBody (std::vector< uint8_t > &out, const MessageBody &b)
MessageBody readMessageBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomCreatedBody (std::vector< uint8_t > &out, const RoomCreatedBody &b)
RoomCreatedBody readRoomCreatedBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomJoinedBody (std::vector< uint8_t > &out, const RoomJoinedBody &b)
RoomJoinedBody readRoomJoinedBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomLeftBody (std::vector< uint8_t > &out, const RoomLeftBody &b)
RoomLeftBody readRoomLeftBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomListBody (std::vector< uint8_t > &out, const RoomListBody &b)
RoomListBody readRoomListBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomMessageBody (std::vector< uint8_t > &out, const RoomMessageBody &b)
RoomMessageBody readRoomMessageBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeRoomErrorBody (std::vector< uint8_t > &out, const RoomErrorBody &b)
RoomErrorBody readRoomErrorBody (const uint8_t *data, std::size_t size, std::size_t &off)
void writeString (std::vector< uint8_t > &out, const std::string &str)
std::string readString (const uint8_t *data, std::size_t size, std::size_t &off)
Detailed Description
Definition at line 112 of file Client/include/net/Protocol.hpp.
Constructor & Destructor Documentation
Protocol() [1/2]
RtypeServer::Protocol::Protocol ()
Definition at line 13 of file Server/src/net/Protocol.cpp.
~Protocol() [1/2]
RtypeServer::Protocol::~Protocol ()
Definition at line 18 of file Server/src/net/Protocol.cpp.
Protocol() [2/2]
RtypeServer::Protocol::Protocol ()
~Protocol() [2/2]
RtypeServer::Protocol::~Protocol ()
Member Function Documentation
append_i16be() [1/2]
void RtypeServer::Protocol::append_i16be (std::vector< uint8_t > & out, int16_t v)
append_i16be() [2/2]
void RtypeServer::Protocol::append_i16be (std::vector< uint8_t > & out, int16_t v)
Definition at line 69 of file Server/src/net/Protocol.cpp.
append_u16be() [1/2]
void RtypeServer::Protocol::append_u16be (std::vector< uint8_t > & out, uint16_t v)
append_u16be() [2/2]
void RtypeServer::Protocol::append_u16be (std::vector< uint8_t > & out, uint16_t v)
Definition at line 56 of file Server/src/net/Protocol.cpp.
append_u32be() [1/2]
void RtypeServer::Protocol::append_u32be (std::vector< uint8_t > & out, uint32_t v)
append_u32be() [2/2]
void RtypeServer::Protocol::append_u32be (std::vector< uint8_t > & out, uint32_t v)
Definition at line 62 of file Server/src/net/Protocol.cpp.
append_u8() [1/2]
void RtypeServer::Protocol::append_u8 (std::vector< uint8_t > & out, uint8_t v)
append_u8() [2/2]
void RtypeServer::Protocol::append_u8 (std::vector< uint8_t > & out, uint8_t v)
Definition at line 54 of file Server/src/net/Protocol.cpp.
read_i16be() [1/2]
int16_t RtypeServer::Protocol::read_i16be (const uint8_t * data, std::size_t & off, std::size_t size)
read_i16be() [2/2]
int16_t RtypeServer::Protocol::read_i16be (const uint8_t * data, std::size_t & off, std::size_t size)
Definition at line 102 of file Server/src/net/Protocol.cpp.
read_u16be() [1/2]
uint16_t RtypeServer::Protocol::read_u16be (const uint8_t * data, std::size_t & off, std::size_t size)
read_u16be() [2/2]
uint16_t RtypeServer::Protocol::read_u16be (const uint8_t * data, std::size_t & off, std::size_t size)
Definition at line 84 of file Server/src/net/Protocol.cpp.
read_u32be() [1/2]
uint32_t RtypeServer::Protocol::read_u32be (const uint8_t * data, std::size_t & off, std::size_t size)
read_u32be() [2/2]
uint32_t RtypeServer::Protocol::read_u32be (const uint8_t * data, std::size_t & off, std::size_t size)
Definition at line 93 of file Server/src/net/Protocol.cpp.
read_u8() [1/2]
uint8_t RtypeServer::Protocol::read_u8 (const uint8_t * data, std::size_t & off, std::size_t size)
read_u8() [2/2]
uint8_t RtypeServer::Protocol::read_u8 (const uint8_t * data, std::size_t & off, std::size_t size)
Definition at line 76 of file Server/src/net/Protocol.cpp.
readCreateRoomBody() [1/2]
CreateRoomBody RtypeServer::Protocol::readCreateRoomBody (const uint8_t * data, std::size_t size, std::size_t & off)
readCreateRoomBody() [2/2]
CreateRoomBody RtypeServer::Protocol::readCreateRoomBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 173 of file Server/src/net/Protocol.cpp.
References RtypeServer::CreateRoomBody::roomName.
readHeader() [1/2]
NetHeader RtypeServer::Protocol::readHeader (const uint8_t * data, std::size_t size)
readHeader() [2/2]
NetHeader RtypeServer::Protocol::readHeader (const uint8_t * data, std::size_t size)
Definition at line 37 of file Server/src/net/Protocol.cpp.
Referenced by NetworkClient::processMessage().
readHelloBody() [1/2]
HelloBody RtypeServer::Protocol::readHelloBody (const uint8_t * data, std::size_t size, std::size_t & off)
readHelloBody() [2/2]
HelloBody RtypeServer::Protocol::readHelloBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 120 of file Server/src/net/Protocol.cpp.
References RtypeServer::HelloBody::client_nonce.
readJoinRoomBody() [1/2]
JoinRoomBody RtypeServer::Protocol::readJoinRoomBody (const uint8_t * data, std::size_t size, std::size_t & off)
readJoinRoomBody() [2/2]
JoinRoomBody RtypeServer::Protocol::readJoinRoomBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 186 of file Server/src/net/Protocol.cpp.
References RtypeServer::JoinRoomBody::roomName.
readMessageBody() [1/2]
MessageBody RtypeServer::Protocol::readMessageBody (const uint8_t * data, std::size_t size, std::size_t & off)
readMessageBody() [2/2]
MessageBody RtypeServer::Protocol::readMessageBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 198 of file Server/src/net/Protocol.cpp.
References RtypeServer::MessageBody::message.
readRoomCreatedBody() [1/2]
RoomCreatedBody RtypeServer::Protocol::readRoomCreatedBody (const uint8_t * data, std::size_t size, std::size_t & off)
readRoomCreatedBody() [2/2]
RoomCreatedBody RtypeServer::Protocol::readRoomCreatedBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 212 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomCreatedBody::roomId.
Referenced by NetworkClient::processMessage().
readRoomErrorBody() [1/2]
RoomErrorBody RtypeServer::Protocol::readRoomErrorBody (const uint8_t * data, std::size_t size, std::size_t & off)
readRoomErrorBody() [2/2]
RoomErrorBody RtypeServer::Protocol::readRoomErrorBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 303 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomErrorBody::errorCode.
Referenced by NetworkClient::processMessage().
readRoomJoinedBody() [1/2]
RoomJoinedBody RtypeServer::Protocol::readRoomJoinedBody (const uint8_t * data, std::size_t size, std::size_t & off)
readRoomJoinedBody() [2/2]
RoomJoinedBody RtypeServer::Protocol::readRoomJoinedBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 229 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomJoinedBody::roomId.
Referenced by NetworkClient::processMessage().
readRoomLeftBody() [1/2]
RoomLeftBody RtypeServer::Protocol::readRoomLeftBody (const uint8_t * data, std::size_t size, std::size_t & off)
readRoomLeftBody() [2/2]
RoomLeftBody RtypeServer::Protocol::readRoomLeftBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 245 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomLeftBody::roomId.
Referenced by NetworkClient::processMessage().
readRoomListBody() [1/2]
RoomListBody RtypeServer::Protocol::readRoomListBody (const uint8_t * data, std::size_t size, std::size_t & off)
readRoomListBody() [2/2]
RoomListBody RtypeServer::Protocol::readRoomListBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 264 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomInfoEntry::roomId.
Referenced by NetworkClient::processMessage().
readRoomMessageBody() [1/2]
RoomMessageBody RtypeServer::Protocol::readRoomMessageBody (const uint8_t * data, std::size_t size, std::size_t & off)
readRoomMessageBody() [2/2]
RoomMessageBody RtypeServer::Protocol::readRoomMessageBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 288 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomMessageBody::senderId.
Referenced by NetworkClient::processMessage().
readString() [1/2]
std::string RtypeServer::Protocol::readString (const uint8_t * data, std::size_t size, std::size_t & off)
readString() [2/2]
std::string RtypeServer::Protocol::readString (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 157 of file Server/src/net/Protocol.cpp.
readWelcomeBody() [1/2]
WelcomeBody RtypeServer::Protocol::readWelcomeBody (const uint8_t * data, std::size_t size, std::size_t & off)
readWelcomeBody() [2/2]
WelcomeBody RtypeServer::Protocol::readWelcomeBody (const uint8_t * data, std::size_t size, std::size_t & off)
Definition at line 141 of file Server/src/net/Protocol.cpp.
References RtypeServer::WelcomeBody::playerId.
Referenced by NetworkClient::processMessage().
writeCreateRoomBody() [1/2]
void RtypeServer::Protocol::writeCreateRoomBody (std::vector< uint8_t > & out, const CreateRoomBody & b)
writeCreateRoomBody() [2/2]
void RtypeServer::Protocol::writeCreateRoomBody (std::vector< uint8_t > & out, const CreateRoomBody & b)
Definition at line 167 of file Server/src/net/Protocol.cpp.
References RtypeServer::CreateRoomBody::maxPlayers, and RtypeServer::CreateRoomBody::roomName.
Referenced by NetworkClient::createRoom().
writeHeader() [1/2]
void RtypeServer::Protocol::writeHeader (std::vector< uint8_t > & out, const NetHeader & h)
writeHeader() [2/2]
void RtypeServer::Protocol::writeHeader (std::vector< uint8_t > & out, const NetHeader & h)
Definition at line 22 of file Server/src/net/Protocol.cpp.
References RtypeServer::NetHeader::ack, RtypeServer::NetHeader::ackBits, RtypeServer::NetHeader::magic, RtypeServer::NetHeader::seq, RtypeServer::NetHeader::type, and RtypeServer::NetHeader::version.
Referenced by NetworkClient::connect(), NetworkClient::createRoom(), RtypeServer::UdpServer::handle_message(), NetworkClient::joinRoom(), NetworkClient::leaveRoom(), NetworkClient::listRooms(), RtypeServer::UdpServer::send_ping(), RtypeServer::UdpServer::send_pong(), RtypeServer::UdpServer::send_room_created(), RtypeServer::UdpServer::send_room_error(), RtypeServer::UdpServer::send_room_joined(), RtypeServer::UdpServer::send_room_left(), RtypeServer::UdpServer::send_room_list(), RtypeServer::UdpServer::send_welcome(), and NetworkClient::sendMessage().
writeHelloBody() [1/2]
void RtypeServer::Protocol::writeHelloBody (std::vector< uint8_t > & out, const HelloBody & b)
writeHelloBody() [2/2]
void RtypeServer::Protocol::writeHelloBody (std::vector< uint8_t > & out, const HelloBody & b)
Definition at line 110 of file Server/src/net/Protocol.cpp.
References RtypeServer::HelloBody::client_nonce, RtypeServer::HelloBody::name, and RtypeServer::HelloBody::proto.
Referenced by NetworkClient::connect().
writeJoinRoomBody() [1/2]
void RtypeServer::Protocol::writeJoinRoomBody (std::vector< uint8_t > & out, const JoinRoomBody & b)
writeJoinRoomBody() [2/2]
void RtypeServer::Protocol::writeJoinRoomBody (std::vector< uint8_t > & out, const JoinRoomBody & b)
Definition at line 181 of file Server/src/net/Protocol.cpp.
References RtypeServer::JoinRoomBody::roomName.
Referenced by NetworkClient::joinRoom().
writeMessageBody() [1/2]
void RtypeServer::Protocol::writeMessageBody (std::vector< uint8_t > & out, const MessageBody & b)
writeMessageBody() [2/2]
void RtypeServer::Protocol::writeMessageBody (std::vector< uint8_t > & out, const MessageBody & b)
Definition at line 193 of file Server/src/net/Protocol.cpp.
References RtypeServer::MessageBody::message.
Referenced by NetworkClient::sendMessage().
writeRoomCreatedBody() [1/2]
void RtypeServer::Protocol::writeRoomCreatedBody (std::vector< uint8_t > & out, const RoomCreatedBody & b)
writeRoomCreatedBody() [2/2]
void RtypeServer::Protocol::writeRoomCreatedBody (std::vector< uint8_t > & out, const RoomCreatedBody & b)
Definition at line 205 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomCreatedBody::roomId, RtypeServer::RoomCreatedBody::roomName, and RtypeServer::RoomCreatedBody::success.
Referenced by RtypeServer::UdpServer::send_room_created().
writeRoomErrorBody() [1/2]
void RtypeServer::Protocol::writeRoomErrorBody (std::vector< uint8_t > & out, const RoomErrorBody & b)
writeRoomErrorBody() [2/2]
void RtypeServer::Protocol::writeRoomErrorBody (std::vector< uint8_t > & out, const RoomErrorBody & b)
Definition at line 297 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomErrorBody::errorCode, and RtypeServer::RoomErrorBody::errorMessage.
Referenced by RtypeServer::UdpServer::send_room_error().
writeRoomJoinedBody() [1/2]
void RtypeServer::Protocol::writeRoomJoinedBody (std::vector< uint8_t > & out, const RoomJoinedBody & b)
writeRoomJoinedBody() [2/2]
void RtypeServer::Protocol::writeRoomJoinedBody (std::vector< uint8_t > & out, const RoomJoinedBody & b)
Definition at line 221 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomJoinedBody::playerCount, RtypeServer::RoomJoinedBody::roomId, RtypeServer::RoomJoinedBody::roomName, and RtypeServer::RoomJoinedBody::success.
Referenced by RtypeServer::UdpServer::send_room_joined().
writeRoomLeftBody() [1/2]
void RtypeServer::Protocol::writeRoomLeftBody (std::vector< uint8_t > & out, const RoomLeftBody & b)
writeRoomLeftBody() [2/2]
void RtypeServer::Protocol::writeRoomLeftBody (std::vector< uint8_t > & out, const RoomLeftBody & b)
Definition at line 239 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomLeftBody::roomId, and RtypeServer::RoomLeftBody::success.
Referenced by RtypeServer::UdpServer::send_room_left().
writeRoomListBody() [1/2]
void RtypeServer::Protocol::writeRoomListBody (std::vector< uint8_t > & out, const RoomListBody & b)
writeRoomListBody() [2/2]
void RtypeServer::Protocol::writeRoomListBody (std::vector< uint8_t > & out, const RoomListBody & b)
Definition at line 253 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomListBody::rooms.
Referenced by RtypeServer::UdpServer::send_room_list().
writeRoomMessageBody() [1/2]
void RtypeServer::Protocol::writeRoomMessageBody (std::vector< uint8_t > & out, const RoomMessageBody & b)
writeRoomMessageBody() [2/2]
void RtypeServer::Protocol::writeRoomMessageBody (std::vector< uint8_t > & out, const RoomMessageBody & b)
Definition at line 281 of file Server/src/net/Protocol.cpp.
References RtypeServer::RoomMessageBody::message, RtypeServer::RoomMessageBody::senderId, and RtypeServer::RoomMessageBody::senderName.
Referenced by RtypeServer::UdpServer::handle_message().
writeString() [1/2]
void RtypeServer::Protocol::writeString (std::vector< uint8_t > & out, const std::string & str)
writeString() [2/2]
void RtypeServer::Protocol::writeString (std::vector< uint8_t > & out, const std::string & str)
Definition at line 150 of file Server/src/net/Protocol.cpp.
writeWelcomeBody() [1/2]
void RtypeServer::Protocol::writeWelcomeBody (std::vector< uint8_t > & out, const WelcomeBody & b)
writeWelcomeBody() [2/2]
void RtypeServer::Protocol::writeWelcomeBody (std::vector< uint8_t > & out, const WelcomeBody & b)
Definition at line 134 of file Server/src/net/Protocol.cpp.
References RtypeServer::WelcomeBody::baselineTick, RtypeServer::WelcomeBody::playerId, and RtypeServer::WelcomeBody::roomId.
Referenced by RtypeServer::UdpServer::send_welcome().
The documentation for this class was generated from the following files:
Server/src/net/Protocol.hpp
Client/include/net/Protocol.hpp
Server/src/net/Protocol.cpp
Client/src/net/Protocol.cpp