R-TYPE: RtypeServer::UdpServer Class Reference
RtypeServer::UdpServer Class Reference
#include <UdpServer.hpp>
Public Member Functions
UdpServer (boost::asio::io_context &io, uint16_t port)
~UdpServer ()
Private Types
using clock = std::chrono::steady_clock
Private Member Functions
void start_receive ()
void handle_receive (std::size_t bytes)
void send_pong (const boost::asio::ip::udp::endpoint &to, uint32_t seq)
void send_welcome (const boost::asio::ip::udp::endpoint &to, uint32_t playerId)
void send_ping (const boost::asio::ip::udp::endpoint &to)
void start_heartbeat ()
void send_room_created (const boost::asio::ip::udp::endpoint &to, uint32_t roomId, const std::string &roomName, bool success)
void send_room_joined (const boost::asio::ip::udp::endpoint &to, uint32_t roomId, const std::string &roomName, bool success, uint8_t playerCount)
void send_room_left (const boost::asio::ip::udp::endpoint &to, uint32_t roomId, bool success)
void send_room_list (const boost::asio::ip::udp::endpoint &to, const std::vector< RoomInfo > &rooms)
void send_room_error (const boost::asio::ip::udp::endpoint &to, uint8_t errorCode, const std::string &message)
void handle_create_room (std::shared_ptr< ClientSession > client, const CreateRoomBody &body)
void handle_join_room (std::shared_ptr< ClientSession > client, const JoinRoomBody &body)
void handle_leave_room (std::shared_ptr< ClientSession > client)
void handle_list_rooms (std::shared_ptr< ClientSession > client)
void handle_message (std::shared_ptr< ClientSession > client, const MessageBody &body)
Static Private Member Functions
static std::string endpointKey (const boost::asio::ip::udp::endpoint &ep)
Private Attributes
boost::asio::ip::udp::socket m_socket
boost::asio::ip::udp::endpoint m_remote
std::array< uint8_t, 1500 > m_rxBuf
boost::asio::steady_timer m_timer
uint32_t m_nextPlayerId = 1
std::unordered_map< std::string, std::shared_ptr< ClientSession > > m_sessions
Protocol m_protocol
RoomManager m_roomManager
Detailed Description
Definition at line 23 of file UdpServer.hpp.
Member Typedef Documentation
clock
using RtypeServer::UdpServer::clock = std::chrono::steady_clock private
Definition at line 25 of file UdpServer.hpp.
Constructor & Destructor Documentation
UdpServer()
RtypeServer::UdpServer::UdpServer (boost::asio::io_context & io, uint16_t port)
Definition at line 18 of file UdpServer.cpp.
References RtypeServer::infof(), m_roomManager, m_socket, RtypeServer::RoomManager::setSocket(), start_heartbeat(), and start_receive().
~UdpServer()
RtypeServer::UdpServer::~UdpServer ()
Definition at line 27 of file UdpServer.cpp.
Member Function Documentation
endpointKey()
std::string RtypeServer::UdpServer::endpointKey (const boost::asio::ip::udp::endpoint & ep) static private
Definition at line 233 of file UdpServer.cpp.
handle_create_room()
void RtypeServer::UdpServer::handle_create_room (std::shared_ptr< ClientSession > client, const CreateRoomBody & body) private
Definition at line 384 of file UdpServer.cpp.
References RtypeServer::RoomManager::createRoom(), handle_join_room(), RtypeServer::infof(), m_roomManager, RtypeServer::CreateRoomBody::maxPlayers, RtypeServer::RoomManager::roomExists(), RtypeServer::CreateRoomBody::roomName, send_room_created(), and send_room_error().
handle_join_room()
void RtypeServer::UdpServer::handle_join_room (std::shared_ptr< ClientSession > client, const JoinRoomBody & body) private
Definition at line 406 of file UdpServer.cpp.
References RtypeServer::RoomManager::getRoom(), RtypeServer::infof(), RtypeServer::RoomManager::joinRoom(), m_roomManager, RtypeServer::RoomManager::roomExists(), RtypeServer::JoinRoomBody::roomName, send_room_error(), and send_room_joined().
Referenced by handle_create_room().
handle_leave_room()
void RtypeServer::UdpServer::handle_leave_room (std::shared_ptr< ClientSession > client) private
Definition at line 435 of file UdpServer.cpp.
References RtypeServer::RoomManager::cleanup(), RtypeServer::infof(), RtypeServer::RoomManager::leaveRoom(), m_roomManager, send_room_error(), and send_room_left().
handle_list_rooms()
void RtypeServer::UdpServer::handle_list_rooms (std::shared_ptr< ClientSession > client) private
Definition at line 449 of file UdpServer.cpp.
References RtypeServer::infof(), RtypeServer::RoomManager::listRooms(), m_roomManager, and send_room_list().
handle_message()
void RtypeServer::UdpServer::handle_message (std::shared_ptr< ClientSession > client, const MessageBody & body) private
Definition at line 457 of file UdpServer.cpp.
References RtypeServer::infof(), kMagic, kProtoVersion, m_protocol, RtypeServer::NetHeader::magic, RtypeServer::MessageBody::message, RtypeServer::ROOM_MESSAGE, send_room_error(), RtypeServer::RoomMessageBody::senderId, RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeRoomMessageBody().
handle_receive()
void RtypeServer::UdpServer::handle_receive (std::size_t bytes) private
Definition at line 46 of file UdpServer.cpp.
References RtypeServer::CREATE_ROOM, RtypeServer::HELLO, RtypeServer::infof(), RtypeServer::JOIN_ROOM, kMagic, kProtoVersion, RtypeServer::LEAVE_ROOM, RtypeServer::LIST_ROOMS, RtypeServer::MESSAGE, RtypeServer::PING, RtypeServer::PONG, and RtypeServer::warnf().
send_ping()
void RtypeServer::UdpServer::send_ping (const boost::asio::ip::udp::endpoint & to) private
Definition at line 185 of file UdpServer.cpp.
References kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::PING, RtypeServer::warnf(), and RtypeServer::Protocol::writeHeader().
Referenced by start_heartbeat().
send_pong()
void RtypeServer::UdpServer::send_pong (const boost::asio::ip::udp::endpoint & to, uint32_t seq) private
Definition at line 135 of file UdpServer.cpp.
References kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::PONG, RtypeServer::warnf(), and RtypeServer::Protocol::writeHeader().
send_room_created()
void RtypeServer::UdpServer::send_room_created (const boost::asio::ip::udp::endpoint & to, uint32_t roomId, const std::string & roomName, bool success) private
Definition at line 238 of file UdpServer.cpp.
References RtypeServer::infof(), kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::ROOM_CREATED, RtypeServer::RoomCreatedBody::roomId, RtypeServer::warnf(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeRoomCreatedBody().
Referenced by handle_create_room().
send_room_error()
void RtypeServer::UdpServer::send_room_error (const boost::asio::ip::udp::endpoint & to, uint8_t errorCode, const std::string & message) private
Definition at line 357 of file UdpServer.cpp.
References RtypeServer::RoomErrorBody::errorCode, RtypeServer::infof(), kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::ROOM_ERROR, RtypeServer::warnf(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeRoomErrorBody().
Referenced by handle_create_room(), handle_join_room(), handle_leave_room(), and handle_message().
send_room_joined()
void RtypeServer::UdpServer::send_room_joined (const boost::asio::ip::udp::endpoint & to, uint32_t roomId, const std::string & roomName, bool success, uint8_t playerCount) private
Definition at line 266 of file UdpServer.cpp.
References RtypeServer::infof(), kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::ROOM_JOINED, RtypeServer::RoomJoinedBody::roomId, RtypeServer::warnf(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeRoomJoinedBody().
Referenced by handle_join_room().
send_room_left()
void RtypeServer::UdpServer::send_room_left (const boost::asio::ip::udp::endpoint & to, uint32_t roomId, bool success) private
Definition at line 295 of file UdpServer.cpp.
References RtypeServer::infof(), kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::ROOM_LEFT, RtypeServer::RoomLeftBody::roomId, RtypeServer::warnf(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeRoomLeftBody().
Referenced by handle_leave_room().
send_room_list()
void RtypeServer::UdpServer::send_room_list (const boost::asio::ip::udp::endpoint & to, const std::vector< RoomInfo > & rooms) private
Definition at line 322 of file UdpServer.cpp.
References RtypeServer::infof(), kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::ROOM_LIST, RtypeServer::RoomInfoEntry::roomId, RtypeServer::warnf(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeRoomListBody().
Referenced by handle_list_rooms().
send_welcome()
void RtypeServer::UdpServer::send_welcome (const boost::asio::ip::udp::endpoint & to, uint32_t playerId) private
Definition at line 156 of file UdpServer.cpp.
References RtypeServer::infof(), kMagic, kProtoVersion, m_protocol, m_socket, RtypeServer::NetHeader::magic, RtypeServer::WelcomeBody::playerId, RtypeServer::warnf(), RtypeServer::WELCOME, RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeWelcomeBody().
start_heartbeat()
void RtypeServer::UdpServer::start_heartbeat () private
Definition at line 205 of file UdpServer.cpp.
References RtypeServer::infof(), m_sessions, m_socket, m_timer, send_ping(), and start_heartbeat().
Referenced by start_heartbeat(), and UdpServer().
start_receive()
void RtypeServer::UdpServer::start_receive () private
Definition at line 31 of file UdpServer.cpp.
References RtypeServer::warnf().
Referenced by UdpServer().
Member Data Documentation
m_nextPlayerId
uint32_t RtypeServer::UdpServer::m_nextPlayerId = 1 private
Definition at line 55 of file UdpServer.hpp.
m_protocol
Protocol RtypeServer::UdpServer::m_protocol private
Definition at line 57 of file UdpServer.hpp.
Referenced by handle_message(), send_ping(), send_pong(), send_room_created(), send_room_error(), send_room_joined(), send_room_left(), send_room_list(), and send_welcome().
m_remote
boost::asio::ip::udp::endpoint RtypeServer::UdpServer::m_remote private
Definition at line 52 of file UdpServer.hpp.
m_roomManager
RoomManager RtypeServer::UdpServer::m_roomManager private
Definition at line 58 of file UdpServer.hpp.
Referenced by handle_create_room(), handle_join_room(), handle_leave_room(), handle_list_rooms(), and UdpServer().
m_rxBuf
std::array<uint8_t, 1500> RtypeServer::UdpServer::m_rxBuf private
Definition at line 53 of file UdpServer.hpp.
m_sessions
std::unordered_map<std::string, std::shared_ptr<ClientSession> > RtypeServer::UdpServer::m_sessions private
Definition at line 56 of file UdpServer.hpp.
Referenced by start_heartbeat().
m_socket
boost::asio::ip::udp::socket RtypeServer::UdpServer::m_socket private
Definition at line 51 of file UdpServer.hpp.
Referenced by send_ping(), send_pong(), send_room_created(), send_room_error(), send_room_joined(), send_room_left(), send_room_list(), send_welcome(), start_heartbeat(), and UdpServer().
m_timer
boost::asio::steady_timer RtypeServer::UdpServer::m_timer private
Definition at line 54 of file UdpServer.hpp.
Referenced by start_heartbeat().
The documentation for this class was generated from the following files:
UdpServer.hpp
UdpServer.cpp