R-TYPE: NetworkClient Class Reference
NetworkClient Class Reference
#include <NetworkClient.hpp>
Public Types
using ConnectedCallback = std::function<void(uint32_t playerId)>
using RoomCreatedCallback = std::function<void(const RoomCreatedBody&)>
using RoomJoinedCallback = std::function<void(const RoomJoinedBody&)>
using RoomLeftCallback = std::function<void(const RoomLeftBody&)>
using RoomListCallback = std::function<void(const RoomListBody&)>
using RoomMessageCallback = std::function<void(const RoomMessageBody&)>
using RoomErrorCallback = std::function<void(const RoomErrorBody&)>
Public Member Functions
NetworkClient ()
~NetworkClient ()
bool connect (const std::string &serverIP, uint16_t port, const std::string &playerName)
void disconnect ()
bool isConnected () const
void createRoom (const std::string &roomName, uint8_t maxPlayers=4)
void joinRoom (const std::string &roomName)
void leaveRoom ()
void listRooms ()
void sendMessage (const std::string &message)
void setConnectedCallback (ConnectedCallback cb)
void setRoomCreatedCallback (RoomCreatedCallback cb)
void setRoomJoinedCallback (RoomJoinedCallback cb)
void setRoomLeftCallback (RoomLeftCallback cb)
void setRoomListCallback (RoomListCallback cb)
void setRoomMessageCallback (RoomMessageCallback cb)
void setRoomErrorCallback (RoomErrorCallback cb)
uint32_t getPlayerId () const
const std::string & getPlayerName () const
Private Member Functions
void networkThread ()
void startReceive ()
void handleReceive (const boost::system::error_code &error, std::size_t bytes)
void sendPacket (const std::vector< uint8_t > &data)
void processMessage (const uint8_t *data, std::size_t size)
Private Attributes
std::unique_ptr< boost::asio::io_context > m_io
std::unique_ptr< udp::socket > m_socket
udp::endpoint m_serverEndpoint
std::array< uint8_t, 1500 > m_rxBuffer
Protocol m_protocol
std::atomic< bool > m_connected {false}
std::atomic< bool > m_running {false}
std::unique_ptr< std::thread > m_networkThread
uint32_t m_playerId = 0
std::string m_playerName
ConnectedCallback m_onConnected
RoomCreatedCallback m_onRoomCreated
RoomJoinedCallback m_onRoomJoined
RoomLeftCallback m_onRoomLeft
RoomListCallback m_onRoomList
RoomMessageCallback m_onRoomMessage
RoomErrorCallback m_onRoomError
Detailed Description
Definition at line 24 of file NetworkClient.hpp.
Member Typedef Documentation
ConnectedCallback
using NetworkClient::ConnectedCallback = std::function<void(uint32_t playerId)>
Definition at line 26 of file NetworkClient.hpp.
RoomCreatedCallback
using NetworkClient::RoomCreatedCallback = std::function<void(const RoomCreatedBody&)>
Definition at line 27 of file NetworkClient.hpp.
RoomErrorCallback
using NetworkClient::RoomErrorCallback = std::function<void(const RoomErrorBody&)>
Definition at line 32 of file NetworkClient.hpp.
RoomJoinedCallback
using NetworkClient::RoomJoinedCallback = std::function<void(const RoomJoinedBody&)>
Definition at line 28 of file NetworkClient.hpp.
RoomLeftCallback
using NetworkClient::RoomLeftCallback = std::function<void(const RoomLeftBody&)>
Definition at line 29 of file NetworkClient.hpp.
RoomListCallback
using NetworkClient::RoomListCallback = std::function<void(const RoomListBody&)>
Definition at line 30 of file NetworkClient.hpp.
RoomMessageCallback
using NetworkClient::RoomMessageCallback = std::function<void(const RoomMessageBody&)>
Definition at line 31 of file NetworkClient.hpp.
Constructor & Destructor Documentation
NetworkClient()
NetworkClient::NetworkClient ()
Definition at line 23 of file NetworkClient.cpp.
~NetworkClient()
NetworkClient::~NetworkClient ()
Definition at line 25 of file NetworkClient.cpp.
References disconnect().
Member Function Documentation
connect()
bool NetworkClient::connect (const std::string & serverIP, uint16_t port, const std::string & playerName)
Definition at line 30 of file NetworkClient.cpp.
References RtypeServer::HelloBody::client_nonce, kMagic, kProtoVersion, m_connected, m_io, m_networkThread, m_playerName, m_protocol, m_running, m_serverEndpoint, m_socket, RtypeServer::NetHeader::magic, networkThread(), sendPacket(), startReceive(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeHelloBody().
createRoom()
void NetworkClient::createRoom (const std::string & roomName, uint8_t maxPlayers = 4)
Definition at line 81 of file NetworkClient.cpp.
References kMagic, kProtoVersion, m_connected, m_protocol, RtypeServer::NetHeader::magic, RtypeServer::CreateRoomBody::roomName, sendPacket(), RtypeServer::Protocol::writeCreateRoomBody(), and RtypeServer::Protocol::writeHeader().
disconnect()
void NetworkClient::disconnect ()
Definition at line 63 of file NetworkClient.cpp.
References m_connected, m_io, m_networkThread, m_running, and m_socket.
Referenced by ~NetworkClient().
getPlayerId()
uint32_t NetworkClient::getPlayerId () const inline
Definition at line 55 of file NetworkClient.hpp.
References m_playerId.
getPlayerName()
const std::string & NetworkClient::getPlayerName () const inline
Definition at line 56 of file NetworkClient.hpp.
References m_playerName.
handleReceive()
void NetworkClient::handleReceive (const boost::system::error_code & error, std::size_t bytes) private
Definition at line 145 of file NetworkClient.cpp.
References m_running, m_rxBuffer, processMessage(), and startReceive().
Referenced by startReceive().
isConnected()
bool NetworkClient::isConnected () const inline
Definition at line 39 of file NetworkClient.hpp.
References m_connected.
joinRoom()
void NetworkClient::joinRoom (const std::string & roomName)
Definition at line 93 of file NetworkClient.cpp.
References kMagic, kProtoVersion, m_connected, m_protocol, RtypeServer::NetHeader::magic, RtypeServer::JoinRoomBody::roomName, sendPacket(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeJoinRoomBody().
leaveRoom()
void NetworkClient::leaveRoom ()
Definition at line 102 of file NetworkClient.cpp.
References kMagic, kProtoVersion, m_connected, m_protocol, RtypeServer::NetHeader::magic, sendPacket(), and RtypeServer::Protocol::writeHeader().
listRooms()
void NetworkClient::listRooms ()
Definition at line 110 of file NetworkClient.cpp.
References kMagic, kProtoVersion, m_connected, m_protocol, RtypeServer::NetHeader::magic, sendPacket(), and RtypeServer::Protocol::writeHeader().
Referenced by processMessage().
networkThread()
void NetworkClient::networkThread () private
Definition at line 127 of file NetworkClient.cpp.
References m_io.
Referenced by connect().
processMessage()
void NetworkClient::processMessage (const uint8_t * data, std::size_t size) private
Definition at line 166 of file NetworkClient.cpp.
References kMagic, kProtoVersion, listRooms(), m_connected, m_onConnected, m_onRoomCreated, m_onRoomError, m_onRoomJoined, m_onRoomLeft, m_onRoomList, m_onRoomMessage, m_playerId, m_protocol, RtypeServer::NetHeader::magic, RtypeServer::WelcomeBody::playerId, RtypeServer::Protocol::readHeader(), RtypeServer::Protocol::readRoomCreatedBody(), RtypeServer::Protocol::readRoomErrorBody(), RtypeServer::Protocol::readRoomJoinedBody(), RtypeServer::Protocol::readRoomLeftBody(), RtypeServer::Protocol::readRoomListBody(), RtypeServer::Protocol::readRoomMessageBody(), RtypeServer::Protocol::readWelcomeBody(), RtypeServer::NetHeader::type, and RtypeServer::NetHeader::version.
Referenced by handleReceive().
sendMessage()
void NetworkClient::sendMessage (const std::string & message)
Definition at line 118 of file NetworkClient.cpp.
References kMagic, kProtoVersion, m_connected, m_protocol, RtypeServer::NetHeader::magic, RtypeServer::MessageBody::message, sendPacket(), RtypeServer::Protocol::writeHeader(), and RtypeServer::Protocol::writeMessageBody().
sendPacket()
void NetworkClient::sendPacket (const std::vector< uint8_t > & data) private
Definition at line 155 of file NetworkClient.cpp.
References m_serverEndpoint, m_socket, and s_sendMutex.
Referenced by connect(), createRoom(), joinRoom(), leaveRoom(), listRooms(), and sendMessage().
setConnectedCallback()
void NetworkClient::setConnectedCallback (ConnectedCallback cb) inline
Definition at line 47 of file NetworkClient.hpp.
References m_onConnected.
setRoomCreatedCallback()
void NetworkClient::setRoomCreatedCallback (RoomCreatedCallback cb) inline
Definition at line 48 of file NetworkClient.hpp.
References m_onRoomCreated.
setRoomErrorCallback()
void NetworkClient::setRoomErrorCallback (RoomErrorCallback cb) inline
Definition at line 53 of file NetworkClient.hpp.
References m_onRoomError.
setRoomJoinedCallback()
void NetworkClient::setRoomJoinedCallback (RoomJoinedCallback cb) inline
Definition at line 49 of file NetworkClient.hpp.
References m_onRoomJoined.
setRoomLeftCallback()
void NetworkClient::setRoomLeftCallback (RoomLeftCallback cb) inline
Definition at line 50 of file NetworkClient.hpp.
References m_onRoomLeft.
setRoomListCallback()
void NetworkClient::setRoomListCallback (RoomListCallback cb) inline
Definition at line 51 of file NetworkClient.hpp.
References m_onRoomList.
setRoomMessageCallback()
void NetworkClient::setRoomMessageCallback (RoomMessageCallback cb) inline
Definition at line 52 of file NetworkClient.hpp.
References m_onRoomMessage.
startReceive()
void NetworkClient::startReceive () private
Definition at line 136 of file NetworkClient.cpp.
References handleReceive(), m_rxBuffer, m_serverEndpoint, and m_socket.
Referenced by connect(), and handleReceive().
Member Data Documentation
m_connected
std::atomic<bool> NetworkClient::m_connected {false} private
Definition at line 72 of file NetworkClient.hpp.
Referenced by connect(), createRoom(), disconnect(), isConnected(), joinRoom(), leaveRoom(), listRooms(), processMessage(), and sendMessage().
m_io
std::unique_ptr<boost::asio::io_context> NetworkClient::m_io private
Definition at line 66 of file NetworkClient.hpp.
Referenced by connect(), disconnect(), and networkThread().
m_networkThread
std::unique_ptr<std::thread> NetworkClient::m_networkThread private
Definition at line 74 of file NetworkClient.hpp.
Referenced by connect(), and disconnect().
m_onConnected
ConnectedCallback NetworkClient::m_onConnected private
Definition at line 79 of file NetworkClient.hpp.
Referenced by processMessage(), and setConnectedCallback().
m_onRoomCreated
RoomCreatedCallback NetworkClient::m_onRoomCreated private
Definition at line 80 of file NetworkClient.hpp.
Referenced by processMessage(), and setRoomCreatedCallback().
m_onRoomError
RoomErrorCallback NetworkClient::m_onRoomError private
Definition at line 85 of file NetworkClient.hpp.
Referenced by processMessage(), and setRoomErrorCallback().
m_onRoomJoined
RoomJoinedCallback NetworkClient::m_onRoomJoined private
Definition at line 81 of file NetworkClient.hpp.
Referenced by processMessage(), and setRoomJoinedCallback().
m_onRoomLeft
RoomLeftCallback NetworkClient::m_onRoomLeft private
Definition at line 82 of file NetworkClient.hpp.
Referenced by processMessage(), and setRoomLeftCallback().
m_onRoomList
RoomListCallback NetworkClient::m_onRoomList private
Definition at line 83 of file NetworkClient.hpp.
Referenced by processMessage(), and setRoomListCallback().
m_onRoomMessage
RoomMessageCallback NetworkClient::m_onRoomMessage private
Definition at line 84 of file NetworkClient.hpp.
Referenced by processMessage(), and setRoomMessageCallback().
m_playerId
uint32_t NetworkClient::m_playerId = 0 private
Definition at line 76 of file NetworkClient.hpp.
Referenced by getPlayerId(), and processMessage().
m_playerName
std::string NetworkClient::m_playerName private
Definition at line 77 of file NetworkClient.hpp.
Referenced by connect(), and getPlayerName().
m_protocol
Protocol NetworkClient::m_protocol private
Definition at line 70 of file NetworkClient.hpp.
Referenced by connect(), createRoom(), joinRoom(), leaveRoom(), listRooms(), processMessage(), and sendMessage().
m_running
std::atomic<bool> NetworkClient::m_running {false} private
Definition at line 73 of file NetworkClient.hpp.
Referenced by connect(), disconnect(), and handleReceive().
m_rxBuffer
std::array<uint8_t, 1500> NetworkClient::m_rxBuffer private
Definition at line 69 of file NetworkClient.hpp.
Referenced by handleReceive(), and startReceive().
m_serverEndpoint
udp::endpoint NetworkClient::m_serverEndpoint private
Definition at line 68 of file NetworkClient.hpp.
Referenced by connect(), sendPacket(), and startReceive().
m_socket
std::unique_ptr<udp::socket> NetworkClient::m_socket private
Definition at line 67 of file NetworkClient.hpp.
Referenced by connect(), disconnect(), sendPacket(), and startReceive().
The documentation for this class was generated from the following files:
NetworkClient.hpp
NetworkClient.cpp