R-TYPE: Leaderboard Class Reference
Leaderboard Class Reference
#include <Leaderboard.hpp>
Public Member Functions
Leaderboard (Engine::Utils::Vec2UInt windowSize)
~Leaderboard ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void drawRoundedRectangle (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (Engine::Utils::Vec2UInt newSize)
Public Attributes
sf::RectangleShape leaderboardRectangle
Private Member Functions
void centerImage ()
Private Attributes
sf::IntRect trophyRect
sf::Sprite trophySprite
sf::Texture trophyTexture
Engine::Utils::Vec2UInt windowSize
Detailed Description
Definition at line 17 of file Leaderboard.hpp.
Constructor & Destructor Documentation
Leaderboard()
Leaderboard::Leaderboard (Engine::Utils::Vec2UInt windowSize)
Definition at line 11 of file Leaderboard.cpp.
~Leaderboard()
Leaderboard::~Leaderboard () default
Member Function Documentation
centerImage()
void Leaderboard::centerImage () private
Definition at line 43 of file Leaderboard.cpp.
References trophySprite, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void Leaderboard::draw (sf::RenderWindow & window)
Definition at line 106 of file Leaderboard.cpp.
References drawRoundedRectangle(), leaderboardRectangle, and trophySprite.
Referenced by GameManager::render().
drawRoundedRectangle()
void Leaderboard::drawRoundedRectangle (sf::RenderWindow & window)
Definition at line 54 of file Leaderboard.cpp.
References leaderboardRectangle.
Referenced by draw().
handleEvent()
void Leaderboard::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 122 of file Leaderboard.cpp.
References centerImage(), windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
loadResources()
bool Leaderboard::loadResources ()
Definition at line 15 of file Leaderboard.cpp.
References centerImage(), trophyRect, trophySprite, and trophyTexture.
Referenced by GameManager::GameManager().
update()
void Leaderboard::update ()
Definition at line 137 of file Leaderboard.cpp.
updateWindowSize()
void Leaderboard::updateWindowSize (Engine::Utils::Vec2UInt newSize)
Definition at line 141 of file Leaderboard.cpp.
References centerImage(), and windowSize.
Member Data Documentation
leaderboardRectangle
sf::RectangleShape Leaderboard::leaderboardRectangle
Definition at line 28 of file Leaderboard.hpp.
Referenced by draw(), drawRoundedRectangle(), GameManager::GameManager(), and GameManager::updatePositions().
trophyRect
sf::IntRect Leaderboard::trophyRect private
Definition at line 30 of file Leaderboard.hpp.
Referenced by loadResources().
trophySprite
sf::Sprite Leaderboard::trophySprite private
Definition at line 31 of file Leaderboard.hpp.
Referenced by centerImage(), draw(), and loadResources().
trophyTexture
sf::Texture Leaderboard::trophyTexture private
Definition at line 32 of file Leaderboard.hpp.
Referenced by loadResources().
windowSize
Engine::Utils::Vec2UInt Leaderboard::windowSize private
Definition at line 33 of file Leaderboard.hpp.
Referenced by centerImage(), handleEvent(), and updateWindowSize().
The documentation for this class was generated from the following files:
Leaderboard.hpp
Leaderboard.cpp