R-TYPE: ControlsConfig Class Reference
ControlsConfig Class Reference
#include <ControlsConfig.hpp>
Public Member Functions
ControlsConfig (Engine::Utils::Vec2UInt windowSize)
~ControlsConfig ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (Engine::Utils::Vec2UInt newSize)
sf::Keyboard::Key getControlKey (ControlAction action) const
void setControlKey (ControlAction action, sf::Keyboard::Key key)
std::string getKeyName (sf::Keyboard::Key key) const
bool isWaitingForKeyInput () const
void startKeyCapture (ControlAction action)
void cancelKeyCapture ()
bool isControlButtonClicked (Engine::Utils::Vec2Int mousePos, ControlAction &action) const
Private Member Functions
void setupControlSettings ()
void updateControlSettingsPositions ()
std::string getControlActionName (ControlAction action) const
Private Attributes
sf::Text ControlsTitle
sf::Text ControlLabels [5]
sf::Text ControlValues [5]
sf::RectangleShape ControlButtons [5]
sf::Font FontControlsText
Engine::Utils::Vec2UInt windowSize
std::map< ControlAction, sf::Keyboard::Key > controlKeys
bool waitingForKeyInput
ControlAction currentActionBeingSet
Detailed Description
Definition at line 25 of file ControlsConfig.hpp.
Constructor & Destructor Documentation
ControlsConfig()
ControlsConfig::ControlsConfig (Engine::Utils::Vec2UInt windowSize)
Definition at line 12 of file ControlsConfig.cpp.
References controlKeys, MOVE_DOWN, MOVE_LEFT, MOVE_RIGHT, MOVE_UP, and SHOOT.
~ControlsConfig()
ControlsConfig::~ControlsConfig () default
Member Function Documentation
cancelKeyCapture()
void ControlsConfig::cancelKeyCapture ()
Definition at line 220 of file ControlsConfig.cpp.
References controlKeys, ControlValues, currentActionBeingSet, getKeyName(), and waitingForKeyInput.
Referenced by handleEvent().
draw()
void ControlsConfig::draw (sf::RenderWindow & window)
Definition at line 77 of file ControlsConfig.cpp.
References ControlButtons, ControlLabels, ControlsTitle, ControlValues, FontControlsText, waitingForKeyInput, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by GameManager::render().
getControlActionName()
std::string ControlsConfig::getControlActionName (ControlAction action) const private
Definition at line 243 of file ControlsConfig.cpp.
References MOVE_DOWN, MOVE_LEFT, MOVE_RIGHT, MOVE_UP, and SHOOT.
getControlKey()
sf::Keyboard::Key ControlsConfig::getControlKey (ControlAction action) const
Definition at line 139 of file ControlsConfig.cpp.
References controlKeys.
getKeyName()
std::string ControlsConfig::getKeyName (sf::Keyboard::Key key) const
Definition at line 158 of file ControlsConfig.cpp.
Referenced by cancelKeyCapture(), setControlKey(), and setupControlSettings().
handleEvent()
void ControlsConfig::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 99 of file ControlsConfig.cpp.
References cancelKeyCapture(), ControlValues, currentActionBeingSet, isControlButtonClicked(), setControlKey(), startKeyCapture(), updateControlSettingsPositions(), waitingForKeyInput, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by GameManager::handleEvents().
isControlButtonClicked()
bool ControlsConfig::isControlButtonClicked (Engine::Utils::Vec2Int mousePos, ControlAction & action) const
Definition at line 232 of file ControlsConfig.cpp.
References ControlButtons, Engine::Utils::Vec2Int::x, and Engine::Utils::Vec2Int::y.
Referenced by handleEvent().
isWaitingForKeyInput()
bool ControlsConfig::isWaitingForKeyInput () const
Definition at line 203 of file ControlsConfig.cpp.
References waitingForKeyInput.
loadResources()
bool ControlsConfig::loadResources ()
Definition at line 23 of file ControlsConfig.cpp.
References FontControlsText, and setupControlSettings().
Referenced by GameManager::GameManager().
setControlKey()
void ControlsConfig::setControlKey (ControlAction action, sf::Keyboard::Key key)
Definition at line 148 of file ControlsConfig.cpp.
References controlKeys, ControlValues, and getKeyName().
Referenced by handleEvent().
setupControlSettings()
void ControlsConfig::setupControlSettings () private
Definition at line 33 of file ControlsConfig.cpp.
References ControlButtons, controlKeys, ControlLabels, ControlsTitle, ControlValues, FontControlsText, getKeyName(), and updateControlSettingsPositions().
Referenced by loadResources().
startKeyCapture()
void ControlsConfig::startKeyCapture (ControlAction action)
Definition at line 208 of file ControlsConfig.cpp.
References ControlValues, currentActionBeingSet, and waitingForKeyInput.
Referenced by handleEvent().
update()
void ControlsConfig::update ()
Definition at line 129 of file ControlsConfig.cpp.
updateControlSettingsPositions()
void ControlsConfig::updateControlSettingsPositions () private
Definition at line 61 of file ControlsConfig.cpp.
References ControlButtons, ControlLabels, ControlsTitle, ControlValues, windowSize, and Engine::Utils::Vec2UInt::x.
Referenced by handleEvent(), setupControlSettings(), and updateWindowSize().
updateWindowSize()
void ControlsConfig::updateWindowSize (Engine::Utils::Vec2UInt newSize)
Definition at line 133 of file ControlsConfig.cpp.
References updateControlSettingsPositions(), and windowSize.
Member Data Documentation
ControlButtons
sf::RectangleShape ControlsConfig::ControlButtons[5] private
Definition at line 47 of file ControlsConfig.hpp.
Referenced by draw(), isControlButtonClicked(), setupControlSettings(), and updateControlSettingsPositions().
controlKeys
std::map<ControlAction, sf::Keyboard::Key> ControlsConfig::controlKeys private
Definition at line 51 of file ControlsConfig.hpp.
Referenced by cancelKeyCapture(), ControlsConfig(), getControlKey(), setControlKey(), and setupControlSettings().
ControlLabels
sf::Text ControlsConfig::ControlLabels[5] private
Definition at line 45 of file ControlsConfig.hpp.
Referenced by draw(), setupControlSettings(), and updateControlSettingsPositions().
ControlsTitle
sf::Text ControlsConfig::ControlsTitle private
Definition at line 44 of file ControlsConfig.hpp.
Referenced by draw(), setupControlSettings(), and updateControlSettingsPositions().
ControlValues
sf::Text ControlsConfig::ControlValues[5] private
Definition at line 46 of file ControlsConfig.hpp.
Referenced by cancelKeyCapture(), draw(), handleEvent(), setControlKey(), setupControlSettings(), startKeyCapture(), and updateControlSettingsPositions().
currentActionBeingSet
ControlAction ControlsConfig::currentActionBeingSet private
Definition at line 53 of file ControlsConfig.hpp.
Referenced by cancelKeyCapture(), handleEvent(), and startKeyCapture().
FontControlsText
sf::Font ControlsConfig::FontControlsText private
Definition at line 49 of file ControlsConfig.hpp.
Referenced by draw(), loadResources(), and setupControlSettings().
waitingForKeyInput
bool ControlsConfig::waitingForKeyInput private
Definition at line 52 of file ControlsConfig.hpp.
Referenced by cancelKeyCapture(), draw(), handleEvent(), isWaitingForKeyInput(), and startKeyCapture().
windowSize
Engine::Utils::Vec2UInt ControlsConfig::windowSize private
Definition at line 50 of file ControlsConfig.hpp.
Referenced by draw(), handleEvent(), updateControlSettingsPositions(), and updateWindowSize().
The documentation for this class was generated from the following files:
ControlsConfig.hpp
ControlsConfig.cpp