R-TYPE: Menu Class Reference
Menu Class Reference
#include <Menu.hpp>
Public Member Functions
Menu (Engine::Utils::Vec2UInt windowSize)
~Menu ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (Engine::Utils::Vec2UInt newSize)
Private Member Functions
void centerLogo ()
Private Attributes
sf::Texture logoTexture
sf::Sprite logoSprite
Engine::Utils::Vec2UInt windowSize
Detailed Description
Definition at line 16 of file Menu.hpp.
Constructor & Destructor Documentation
Menu()
Menu::Menu (Engine::Utils::Vec2UInt windowSize)
Definition at line 11 of file Menu.cpp.
~Menu()
Menu::~Menu () default
Member Function Documentation
centerLogo()
void Menu::centerLogo () private
Definition at line 27 of file Menu.cpp.
References logoSprite, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void Menu::draw (sf::RenderWindow & window)
Definition at line 37 of file Menu.cpp.
References logoSprite.
handleEvent()
void Menu::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 42 of file Menu.cpp.
References centerLogo(), windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
loadResources()
bool Menu::loadResources ()
Definition at line 15 of file Menu.cpp.
References centerLogo(), logoSprite, and logoTexture.
update()
void Menu::update ()
Definition at line 57 of file Menu.cpp.
updateWindowSize()
void Menu::updateWindowSize (Engine::Utils::Vec2UInt newSize)
Definition at line 61 of file Menu.cpp.
References centerLogo(), and windowSize.
Member Data Documentation
logoSprite
sf::Sprite Menu::logoSprite private
Definition at line 29 of file Menu.hpp.
Referenced by centerLogo(), draw(), and loadResources().
logoTexture
sf::Texture Menu::logoTexture private
Definition at line 28 of file Menu.hpp.
Referenced by loadResources().
windowSize
Engine::Utils::Vec2UInt Menu::windowSize private
Definition at line 30 of file Menu.hpp.
Referenced by centerLogo(), handleEvent(), and updateWindowSize().
The documentation for this class was generated from the following files:
Menu.hpp
Menu.cpp