R-TYPE: Engine::Event Class Reference
Engine::Event Class Reference
#include <Event.hpp>
Public Member Functions
Event (EventId type)
EventId getType () const
template<typename T >
void setParam (EventId id, T value)
template<typename T >
T getParam (EventId id)
Private Attributes
EventId type {}
std::unordered_map< EventId, std::any > data {}
Detailed Description
Definition at line 34 of file Event.hpp.
Constructor & Destructor Documentation
Event()
Engine::Event::Event (EventId type) inline
Definition at line 36 of file Event.hpp.
Member Function Documentation
getParam()
template<typename T > T Engine::Event::getParam (EventId id)
Definition at line 55 of file Event.hpp.
getType()
EventId Engine::Event::getType () const inline
Definition at line 38 of file Event.hpp.
References type.
setParam()
template<typename T > void Engine::Event::setParam (EventId id, T value)
Definition at line 49 of file Event.hpp.
References data.
Referenced by Engine::Systems::Collision::checkCollision(), Engine::Renderers::SFML::handleEvents(), and Engine::NetworkManager::receiveInputs().
Member Data Documentation
data
std::unordered_map<EventId, std::any> Engine::Event::data {} private
Definition at line 44 of file Event.hpp.
Referenced by setParam().
type
EventId Engine::Event::type {} private
Definition at line 43 of file Event.hpp.
Referenced by getType().
The documentation for this class was generated from the following file:
Event.hpp