R-TYPE: ErrorServer Class Reference
ErrorServer Class Reference
#include <ErrorServer.hpp>
Public Member Functions
ErrorServer (Engine::Utils::Vec2UInt windowSize)
~ErrorServer ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (Engine::Utils::Vec2UInt newSize)
Private Member Functions
void centerLogo ()
Private Attributes
sf::Texture logoTexture
sf::Sprite logoSprite
Engine::Utils::Vec2UInt windowSize
Detailed Description
Definition at line 15 of file ErrorServer.hpp.
Constructor & Destructor Documentation
ErrorServer()
ErrorServer::ErrorServer (Engine::Utils::Vec2UInt windowSize)
Definition at line 11 of file ErrorServer.cpp.
~ErrorServer()
ErrorServer::~ErrorServer () default
Member Function Documentation
centerLogo()
void ErrorServer::centerLogo () private
Definition at line 27 of file ErrorServer.cpp.
References logoSprite, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void ErrorServer::draw (sf::RenderWindow & window)
Definition at line 37 of file ErrorServer.cpp.
References logoSprite.
Referenced by GameManager::render().
handleEvent()
void ErrorServer::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 42 of file ErrorServer.cpp.
References centerLogo(), windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by GameManager::handleEvents().
loadResources()
bool ErrorServer::loadResources ()
Definition at line 15 of file ErrorServer.cpp.
References centerLogo(), logoSprite, and logoTexture.
Referenced by GameManager::GameManager().
update()
void ErrorServer::update ()
Definition at line 57 of file ErrorServer.cpp.
Referenced by GameManager::update().
updateWindowSize()
void ErrorServer::updateWindowSize (Engine::Utils::Vec2UInt newSize)
Definition at line 61 of file ErrorServer.cpp.
References centerLogo(), and windowSize.
Referenced by GameManager::handleWindowResize().
Member Data Documentation
logoSprite
sf::Sprite ErrorServer::logoSprite private
Definition at line 27 of file ErrorServer.hpp.
Referenced by centerLogo(), draw(), and loadResources().
logoTexture
sf::Texture ErrorServer::logoTexture private
Definition at line 26 of file ErrorServer.hpp.
Referenced by loadResources().
windowSize
Engine::Utils::Vec2UInt ErrorServer::windowSize private
Definition at line 28 of file ErrorServer.hpp.
Referenced by centerLogo(), handleEvent(), and updateWindowSize().
The documentation for this class was generated from the following files:
ErrorServer.hpp
ErrorServer.cpp