R-TYPE: Locker Class Reference
Locker Class Reference
#include <Locker.hpp>
Public Member Functions
Locker (sf::Vector2u windowSize)
~Locker ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (sf::Vector2u newSize)
Private Member Functions
void centerLogo ()
Private Attributes
sf::Texture logoTexture
sf::Sprite logoSprite
sf::Vector2u windowSize
Detailed Description
Definition at line 14 of file Locker.hpp.
Constructor & Destructor Documentation
Locker()
Locker::Locker (sf::Vector2u windowSize)
Definition at line 11 of file Locker.cpp.
~Locker()
Locker::~Locker () default
Member Function Documentation
centerLogo()
void Locker::centerLogo () private
Definition at line 27 of file Locker.cpp.
References logoSprite, and windowSize.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void Locker::draw (sf::RenderWindow & window)
Definition at line 37 of file Locker.cpp.
References logoSprite.
handleEvent()
void Locker::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 42 of file Locker.cpp.
References centerLogo(), and windowSize.
loadResources()
bool Locker::loadResources ()
Definition at line 15 of file Locker.cpp.
References centerLogo(), logoSprite, and logoTexture.
update()
void Locker::update ()
Definition at line 57 of file Locker.cpp.
updateWindowSize()
void Locker::updateWindowSize (sf::Vector2u newSize)
Definition at line 61 of file Locker.cpp.
References centerLogo(), and windowSize.
Member Data Documentation
logoSprite
sf::Sprite Locker::logoSprite private
Definition at line 26 of file Locker.hpp.
Referenced by centerLogo(), draw(), and loadResources().
logoTexture
sf::Texture Locker::logoTexture private
Definition at line 25 of file Locker.hpp.
Referenced by loadResources().
windowSize
sf::Vector2u Locker::windowSize private
Definition at line 27 of file Locker.hpp.
Referenced by centerLogo(), handleEvent(), and updateWindowSize().
The documentation for this class was generated from the following files:
Locker.hpp
Locker.cpp