R-TYPE: Lobby Class Reference
Lobby Class Reference
#include <Lobby.hpp>
Public Member Functions
Lobby (Engine::Utils::Vec2UInt windowSize)
~Lobby ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (Engine::Utils::Vec2UInt newSize)
Private Member Functions
void centerLogo ()
Private Attributes
sf::Texture logoTexture
sf::Sprite logoSprite
Engine::Utils::Vec2UInt windowSize
Detailed Description
Definition at line 16 of file Lobby.hpp.
Constructor & Destructor Documentation
Lobby()
Lobby::Lobby (Engine::Utils::Vec2UInt windowSize)
Definition at line 11 of file Lobby.cpp.
~Lobby()
Lobby::~Lobby () default
Member Function Documentation
centerLogo()
void Lobby::centerLogo () private
Definition at line 27 of file Lobby.cpp.
References logoSprite, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void Lobby::draw (sf::RenderWindow & window)
Definition at line 37 of file Lobby.cpp.
References logoSprite.
handleEvent()
void Lobby::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 42 of file Lobby.cpp.
References centerLogo(), windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by GameManager::handleEvents().
loadResources()
bool Lobby::loadResources ()
Definition at line 15 of file Lobby.cpp.
References centerLogo(), logoSprite, and logoTexture.
update()
void Lobby::update ()
Definition at line 57 of file Lobby.cpp.
updateWindowSize()
void Lobby::updateWindowSize (Engine::Utils::Vec2UInt newSize)
Definition at line 61 of file Lobby.cpp.
References centerLogo(), and windowSize.
Member Data Documentation
logoSprite
sf::Sprite Lobby::logoSprite private
Definition at line 28 of file Lobby.hpp.
Referenced by centerLogo(), draw(), and loadResources().
logoTexture
sf::Texture Lobby::logoTexture private
Definition at line 27 of file Lobby.hpp.
Referenced by loadResources().
windowSize
Engine::Utils::Vec2UInt Lobby::windowSize private
Definition at line 29 of file Lobby.hpp.
Referenced by centerLogo(), handleEvent(), and updateWindowSize().
The documentation for this class was generated from the following files:
Lobby.hpp
Lobby.cpp