R-TYPE: Engine::Systems::EnemySystem Class Reference
Engine::Systems::EnemySystem Class Reference
#include <Enemy.hpp>
Public Member Functions
void init (std::shared_ptr< Engine::NetworkManager > networkManager)
void update (std::shared_ptr< Engine::NetworkManager > networkManager, float dt)
Private Member Functions
void handleCollision (std::shared_ptr< Engine::NetworkManager > networkManager, Event &event)
void damageEnemy (std::shared_ptr< Engine::NetworkManager > networkManager, Entity enemy, Entity projectile)
void updateEnemyAI (std::shared_ptr< Engine::NetworkManager > networkManager, Entity enemy, float dt)
Additional Inherited Members
Public Attributes inherited from Engine::System
std::set< Entity > entities {}
Detailed Description
Definition at line 23 of file Enemy.hpp.
Member Function Documentation
damageEnemy()
void Engine::Systems::EnemySystem::damageEnemy (std::shared_ptr< Engine::NetworkManager > networkManager, Entity enemy, Entity projectile) inline private
Definition at line 49 of file Enemy.hpp.
References Engine::Components::Hitbox_s::damage.
Referenced by handleCollision().
handleCollision()
void Engine::Systems::EnemySystem::handleCollision (std::shared_ptr< Engine::NetworkManager > networkManager, Event & event) inline private
Definition at line 37 of file Enemy.hpp.
References damageEnemy(), ENEMY, and PLAYER_PROJECTILE.
Referenced by init().
init()
void Engine::Systems::EnemySystem::init (std::shared_ptr< Engine::NetworkManager > networkManager) inline
Definition at line 25 of file Enemy.hpp.
References Engine::COLLISION, and handleCollision().
Referenced by GameManager::connectToServer(), and main().
update()
void Engine::Systems::EnemySystem::update (std::shared_ptr< Engine::NetworkManager > networkManager, float dt) inline
Definition at line 30 of file Enemy.hpp.
References Engine::System::entities, and updateEnemyAI().
updateEnemyAI()
void Engine::Systems::EnemySystem::updateEnemyAI (std::shared_ptr< Engine::NetworkManager > networkManager, Entity enemy, float dt) inline private
Definition at line 77 of file Enemy.hpp.
References SIMPLE, and SINE_WAVE.
Referenced by update().
The documentation for this class was generated from the following file:
Enemy.hpp