R-TYPE: Engine::Systems::DevConsole Class Reference
Engine::Systems::DevConsole Class Reference
#include <DevConsole.hpp>
Public Member Functions
void init (std::shared_ptr< Mediator > mediator)
void update (std::shared_ptr< NetworkManager > networkManager, std::shared_ptr< Renderer > renderer)
void treatNewTextInput (Event &event)
Private Member Functions
void parseCommand (std::shared_ptr< NetworkManager > networkManager, std::shared_ptr< Renderer > renderer)
template<typename T >
void reflectComponent (std::shared_ptr< NetworkManager > networkManager, Entity entity)
template<typename T >
void setComponentValue (std::shared_ptr< NetworkManager > networkManager, Entity entity, const std::string &component_name, const std::string &field_name, std::string value)
Private Attributes
bool is_open = false
std::string old_std_out = ""
std::string current_command = ""
std::string command_to_parse = ""
uint16_t cursor_pos = 0
std::unordered_map< std::string, std::string > console_vars
Additional Inherited Members
Public Attributes inherited from Engine::System
std::set< Entity > entities {}
Detailed Description
Definition at line 38 of file DevConsole.hpp.
Member Function Documentation
init()
void Engine::Systems::DevConsole::init (std::shared_ptr< Mediator > mediator) inline
Definition at line 40 of file DevConsole.hpp.
References Engine::DEVCONSOLE_KEY_PRESSED, Engine::DEVCONSOLE_TEXT_ENTERED, is_open, and treatNewTextInput().
Referenced by GameManager::connectToServer().
parseCommand()
void Engine::Systems::DevConsole::parseCommand (std::shared_ptr< NetworkManager > networkManager, std::shared_ptr< Renderer > renderer) inline private
Definition at line 96 of file DevConsole.hpp.
References command_to_parse, console_vars, old_std_out, reflectComponent(), and setComponentValue().
Referenced by update().
reflectComponent()
template<typename T > void Engine::Systems::DevConsole::reflectComponent (std::shared_ptr< NetworkManager > networkManager, Entity entity) inline private
Definition at line 184 of file DevConsole.hpp.
References old_std_out.
Referenced by parseCommand().
setComponentValue()
template<typename T > void Engine::Systems::DevConsole::setComponentValue (std::shared_ptr< NetworkManager > networkManager, Entity entity, const std::string & component_name, const std::string & field_name, std::string value) inline private
Definition at line 200 of file DevConsole.hpp.
Referenced by parseCommand().
treatNewTextInput()
void Engine::Systems::DevConsole::treatNewTextInput (Event & event) inline
Definition at line 58 of file DevConsole.hpp.
References command_to_parse, current_command, cursor_pos, Engine::LEFT, old_std_out, and Engine::RIGHT.
Referenced by init().
update()
void Engine::Systems::DevConsole::update (std::shared_ptr< NetworkManager > networkManager, std::shared_ptr< Renderer > renderer) inline
Definition at line 45 of file DevConsole.hpp.
References command_to_parse, current_command, is_open, old_std_out, parseCommand(), Engine::Utils::Vec2::x, and Engine::Utils::Vec2::y.
Member Data Documentation
command_to_parse
std::string Engine::Systems::DevConsole::command_to_parse = "" private
Definition at line 231 of file DevConsole.hpp.
Referenced by parseCommand(), treatNewTextInput(), and update().
console_vars
std::unordered_map<std::string, std::string> Engine::Systems::DevConsole::console_vars private
Definition at line 233 of file DevConsole.hpp.
Referenced by parseCommand().
current_command
std::string Engine::Systems::DevConsole::current_command = "" private
Definition at line 230 of file DevConsole.hpp.
Referenced by treatNewTextInput(), and update().
cursor_pos
uint16_t Engine::Systems::DevConsole::cursor_pos = 0 private
Definition at line 232 of file DevConsole.hpp.
Referenced by treatNewTextInput().
is_open
bool Engine::Systems::DevConsole::is_open = false private
Definition at line 228 of file DevConsole.hpp.
Referenced by init(), and update().
old_std_out
std::string Engine::Systems::DevConsole::old_std_out = "" private
Definition at line 229 of file DevConsole.hpp.
Referenced by parseCommand(), reflectComponent(), treatNewTextInput(), and update().
The documentation for this class was generated from the following file:
DevConsole.hpp