R-TYPE: Parameters Class Reference
Parameters Class Reference
#include <Parameters.hpp>
Public Member Functions
Parameters (Engine::Utils::Vec2UInt windowSize)
~Parameters ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (Engine::Utils::Vec2UInt newSize)
ResolutionMode getCurrentResolution () const
DisplayMode getCurrentDisplayMode () const
GraphicsQuality getCurrentGraphicsQuality () const
ColorBlindMode getCurrentColorBlindMode () const
void setResolution (ResolutionMode resolution)
void setDisplayMode (DisplayMode mode)
void setGraphicsQuality (GraphicsQuality quality)
void setColorBlindMode (ColorBlindMode mode)
Engine::Utils::Vec2UInt getResolutionSize (ResolutionMode resolution) const
sf::Color applyColorBlindFilter (const sf::Color &originalColor) const
Private Member Functions
void centerText ()
void setupVideoSettings ()
void updateVideoSettingsPositions ()
std::string getResolutionString (ResolutionMode resolution) const
std::string getDisplayModeString (DisplayMode mode) const
std::string getGraphicsQualityString (GraphicsQuality quality) const
std::string getColorBlindModeString (ColorBlindMode mode) const
Private Attributes
sf::Text ParamsText
sf::Text VideoSectionTitle
sf::Text ResolutionLabel
sf::Text ResolutionValue
sf::Text DisplayModeLabel
sf::Text DisplayModeValue
sf::Text GraphicsQualityLabel
sf::Text GraphicsQualityValue
sf::Text AccessibilityTitle
sf::Text ColorBlindLabel
sf::Text ColorBlindValue
sf::Font FontParamsText
Engine::Utils::Vec2UInt windowSize
ResolutionMode currentResolution
DisplayMode currentDisplayMode
GraphicsQuality currentGraphicsQuality
ColorBlindMode currentColorBlindMode
Detailed Description
Definition at line 43 of file Parameters.hpp.
Constructor & Destructor Documentation
Parameters()
Parameters::Parameters (Engine::Utils::Vec2UInt windowSize)
Definition at line 12 of file Parameters.cpp.
~Parameters()
Parameters::~Parameters () default
Member Function Documentation
applyColorBlindFilter()
sf::Color Parameters::applyColorBlindFilter (const sf::Color & originalColor) const
Definition at line 261 of file Parameters.cpp.
References currentColorBlindMode, DEUTERANOPIA, MONOCHROME, NORMAL, PROTANOPIA, and TRITANOPIA.
Referenced by draw(), and ParticleSystem::renderParticle().
centerText()
void Parameters::centerText () private
Definition at line 38 of file Parameters.cpp.
References ParamsText, windowSize, and Engine::Utils::Vec2UInt::x.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void Parameters::draw (sf::RenderWindow & window)
Definition at line 48 of file Parameters.cpp.
References AccessibilityTitle, applyColorBlindFilter(), ColorBlindLabel, ColorBlindValue, DisplayModeLabel, DisplayModeValue, GraphicsQualityLabel, GraphicsQualityValue, ParamsText, ResolutionLabel, ResolutionValue, and VideoSectionTitle.
Referenced by GameManager::render().
getColorBlindModeString()
std::string Parameters::getColorBlindModeString (ColorBlindMode mode) const private
Definition at line 215 of file Parameters.cpp.
References DEUTERANOPIA, MONOCHROME, NORMAL, PROTANOPIA, and TRITANOPIA.
Referenced by setColorBlindMode(), and setupVideoSettings().
getCurrentColorBlindMode()
ColorBlindMode Parameters::getCurrentColorBlindMode () const inline
Definition at line 57 of file Parameters.hpp.
References currentColorBlindMode.
Referenced by GameManager::cycleColorBlindMode().
getCurrentDisplayMode()
DisplayMode Parameters::getCurrentDisplayMode () const inline
Definition at line 55 of file Parameters.hpp.
References currentDisplayMode.
Referenced by GameManager::applyCurrentResolution(), and GameManager::cycleDisplayMode().
getCurrentGraphicsQuality()
GraphicsQuality Parameters::getCurrentGraphicsQuality () const inline
Definition at line 56 of file Parameters.hpp.
References currentGraphicsQuality.
Referenced by GameManager::cycleGraphicsQuality().
getCurrentResolution()
ResolutionMode Parameters::getCurrentResolution () const inline
Definition at line 54 of file Parameters.hpp.
References currentResolution.
Referenced by GameManager::applyCurrentResolution(), and GameManager::cycleResolution().
getDisplayModeString()
std::string Parameters::getDisplayModeString (DisplayMode mode) const private
Definition at line 195 of file Parameters.cpp.
References FULLSCREEN, and WINDOWED.
Referenced by setDisplayMode(), and setupVideoSettings().
getGraphicsQualityString()
std::string Parameters::getGraphicsQualityString (GraphicsQuality quality) const private
Definition at line 204 of file Parameters.cpp.
References HIGH, LOW, MEDIUM, and ULTRA.
Referenced by setGraphicsQuality(), and setupVideoSettings().
getResolutionSize()
Engine::Utils::Vec2UInt Parameters::getResolutionSize (ResolutionMode resolution) const
Definition at line 227 of file Parameters.cpp.
References RES_1280x720, RES_1920x1080, and RES_800x600.
Referenced by GameManager::applyCurrentResolution().
getResolutionString()
std::string Parameters::getResolutionString (ResolutionMode resolution) const private
Definition at line 185 of file Parameters.cpp.
References RES_1280x720, RES_1920x1080, and RES_800x600.
Referenced by setResolution(), and setupVideoSettings().
handleEvent()
void Parameters::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 87 of file Parameters.cpp.
References centerText(), windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
loadResources()
bool Parameters::loadResources ()
Definition at line 20 of file Parameters.cpp.
References centerText(), FontParamsText, ParamsText, and setupVideoSettings().
Referenced by GameManager::GameManager().
setColorBlindMode()
void Parameters::setColorBlindMode (ColorBlindMode mode)
Definition at line 255 of file Parameters.cpp.
References ColorBlindValue, currentColorBlindMode, and getColorBlindModeString().
Referenced by GameManager::cycleColorBlindMode().
setDisplayMode()
void Parameters::setDisplayMode (DisplayMode mode)
Definition at line 243 of file Parameters.cpp.
References currentDisplayMode, DisplayModeValue, and getDisplayModeString().
Referenced by GameManager::cycleDisplayMode().
setGraphicsQuality()
void Parameters::setGraphicsQuality (GraphicsQuality quality)
Definition at line 249 of file Parameters.cpp.
References currentGraphicsQuality, getGraphicsQualityString(), and GraphicsQualityValue.
Referenced by GameManager::cycleGraphicsQuality().
setResolution()
void Parameters::setResolution (ResolutionMode resolution)
Definition at line 237 of file Parameters.cpp.
References currentResolution, getResolutionString(), and ResolutionValue.
Referenced by GameManager::cycleResolution().
setupVideoSettings()
void Parameters::setupVideoSettings () private
Definition at line 135 of file Parameters.cpp.
References ColorBlindLabel, ColorBlindValue, currentColorBlindMode, currentDisplayMode, currentGraphicsQuality, currentResolution, DisplayModeLabel, DisplayModeValue, FontParamsText, getColorBlindModeString(), getDisplayModeString(), getGraphicsQualityString(), getResolutionString(), GraphicsQualityLabel, GraphicsQualityValue, ResolutionLabel, ResolutionValue, updateVideoSettingsPositions(), and VideoSectionTitle.
Referenced by loadResources().
update()
void Parameters::update ()
Definition at line 102 of file Parameters.cpp.
updateVideoSettingsPositions()
void Parameters::updateVideoSettingsPositions () private
Definition at line 113 of file Parameters.cpp.
References AccessibilityTitle, ColorBlindLabel, ColorBlindValue, DisplayModeLabel, DisplayModeValue, GraphicsQualityLabel, GraphicsQualityValue, ResolutionLabel, ResolutionValue, VideoSectionTitle, windowSize, and Engine::Utils::Vec2UInt::x.
Referenced by setupVideoSettings(), and updateWindowSize().
updateWindowSize()
void Parameters::updateWindowSize (Engine::Utils::Vec2UInt newSize)
Definition at line 106 of file Parameters.cpp.
References centerText(), updateVideoSettingsPositions(), and windowSize.
Member Data Documentation
AccessibilityTitle
sf::Text Parameters::AccessibilityTitle private
Definition at line 76 of file Parameters.hpp.
Referenced by draw(), and updateVideoSettingsPositions().
ColorBlindLabel
sf::Text Parameters::ColorBlindLabel private
Definition at line 77 of file Parameters.hpp.
Referenced by draw(), setupVideoSettings(), and updateVideoSettingsPositions().
ColorBlindValue
sf::Text Parameters::ColorBlindValue private
Definition at line 78 of file Parameters.hpp.
Referenced by draw(), setColorBlindMode(), setupVideoSettings(), and updateVideoSettingsPositions().
currentColorBlindMode
ColorBlindMode Parameters::currentColorBlindMode private
Definition at line 86 of file Parameters.hpp.
Referenced by applyColorBlindFilter(), getCurrentColorBlindMode(), setColorBlindMode(), and setupVideoSettings().
currentDisplayMode
DisplayMode Parameters::currentDisplayMode private
Definition at line 84 of file Parameters.hpp.
Referenced by getCurrentDisplayMode(), setDisplayMode(), and setupVideoSettings().
currentGraphicsQuality
GraphicsQuality Parameters::currentGraphicsQuality private
Definition at line 85 of file Parameters.hpp.
Referenced by getCurrentGraphicsQuality(), setGraphicsQuality(), and setupVideoSettings().
currentResolution
ResolutionMode Parameters::currentResolution private
Definition at line 83 of file Parameters.hpp.
Referenced by getCurrentResolution(), setResolution(), and setupVideoSettings().
DisplayModeLabel
sf::Text Parameters::DisplayModeLabel private
Definition at line 72 of file Parameters.hpp.
Referenced by draw(), setupVideoSettings(), and updateVideoSettingsPositions().
DisplayModeValue
sf::Text Parameters::DisplayModeValue private
Definition at line 73 of file Parameters.hpp.
Referenced by draw(), setDisplayMode(), setupVideoSettings(), and updateVideoSettingsPositions().
FontParamsText
sf::Font Parameters::FontParamsText private
Definition at line 80 of file Parameters.hpp.
Referenced by loadResources(), and setupVideoSettings().
GraphicsQualityLabel
sf::Text Parameters::GraphicsQualityLabel private
Definition at line 74 of file Parameters.hpp.
Referenced by draw(), setupVideoSettings(), and updateVideoSettingsPositions().
GraphicsQualityValue
sf::Text Parameters::GraphicsQualityValue private
Definition at line 75 of file Parameters.hpp.
Referenced by draw(), setGraphicsQuality(), setupVideoSettings(), and updateVideoSettingsPositions().
ParamsText
sf::Text Parameters::ParamsText private
Definition at line 68 of file Parameters.hpp.
Referenced by centerText(), draw(), and loadResources().
ResolutionLabel
sf::Text Parameters::ResolutionLabel private
Definition at line 70 of file Parameters.hpp.
Referenced by draw(), setupVideoSettings(), and updateVideoSettingsPositions().
ResolutionValue
sf::Text Parameters::ResolutionValue private
Definition at line 71 of file Parameters.hpp.
Referenced by draw(), setResolution(), setupVideoSettings(), and updateVideoSettingsPositions().
VideoSectionTitle
sf::Text Parameters::VideoSectionTitle private
Definition at line 69 of file Parameters.hpp.
Referenced by draw(), setupVideoSettings(), and updateVideoSettingsPositions().
windowSize
Engine::Utils::Vec2UInt Parameters::windowSize private
Definition at line 81 of file Parameters.hpp.
Referenced by centerText(), handleEvent(), updateVideoSettingsPositions(), and updateWindowSize().
The documentation for this class was generated from the following files:
Parameters.hpp
Parameters.cpp