R-TYPE: GameManager Class Reference
GameManager Class Reference
#include <GameTypes.hpp>
Public Member Functions
GameManager (sf::Vector2u windowSize)
~GameManager ()=default
void handleEvents (sf::RenderWindow &window)
void update ()
void render (sf::RenderWindow &window)
bool shouldClose () const
void updatePositions (sf::Vector2u windowSize)
void cycleResolution ()
void cycleDisplayMode (sf::RenderWindow &window)
void cycleGraphicsQuality ()
void cycleColorBlindMode ()
void applyCurrentResolution (sf::RenderWindow &window)
void gameDemo (sf::RenderWindow &window)
void addWaitingPlayer ()
void removeWaitingPlayer ()
int getWaitingPlayersCount () const
State getCurrentState () const
int getCurrentFps () const
void initializeNetworking (const std::string &playerName)
void connectToServerWithRooms (const std::string &serverIP, unsigned short port)
void createRoom (const std::string &roomName, uint8_t maxPlayers=4)
void joinRoom (const std::string &roomName)
void leaveRoom ()
void refreshRoomList ()
void sendRoomMessage (const std::string &message)
Private Member Functions
void handleKeyPress (sf::Event &event, sf::RenderWindow &window)
void handleMouseClick (sf::Event &event, sf::RenderWindow &window)
void handleMouseMove (sf::RenderWindow &window)
void handleWindowResize (sf::Event &event)
void updateStatusTextPosition (bool isParametersMode=false)
bool connectToServer (const std::string &serverIP, unsigned short port)
void onConnected (uint32_t playerId)
void onRoomCreated (const RtypeServer::RoomCreatedBody &body)
void onRoomJoined (const RtypeServer::RoomJoinedBody &body)
void onRoomLeft (const RtypeServer::RoomLeftBody &body)
void onRoomList (const RtypeServer::RoomListBody &body)
void onRoomMessage (const RtypeServer::RoomMessageBody &body)
void onRoomError (const RtypeServer::RoomErrorBody &body)
void renderRoomList (sf::RenderWindow &window)
void renderInRoom (sf::RenderWindow &window)
Private Attributes
Launch launch
Parameters parameters
ControlsConfig controlsConfig
Lobby lobby
ErrorServer errorServer
Player player
ParamButton paramButton
ParamButton fps30Button
ParamButton fps60Button
Button backButton
Button resolutionButton
Button displayModeButton
Button graphicsQualityButton
Button colorBlindModeButton
Button applyResolutionButton
Button controlsButton
Button lockerButton
Button leftButtonSelection
Button rightButtonSelection
Button applyButtonLocker
Button soloButton
Button duoButton
Button trioButton
Button squadButton
Button modeButton
Button playButton
sf::Text numberPlayerToWait
int waitingPlayersCounter
GameMode gameMode
sf::Text statusText
sf::Text fpsDisplay
sf::Font font
sf::Text insertCoinText
sf::Clock insertCoinClock
ParticleSystem particleSystem
sf::Clock deltaClock
std::unique_ptr< NetworkClient > networkClient
std::string playerName
std::vector< RtypeServer::RoomInfoEntry > availableRooms
std::string currentRoomName
bool inRoom
bool waitingRoomAction = false
std::string waitingRoomName
uint8_t waitingRoomMaxPlayers = 1
State currentState
ServerState isConnected
bool isDraggingVolume
bool isChooseMode
bool isConfiguringControls
int currentFps
Detailed Description
Definition at line 53 of file GameTypes.hpp.
Constructor & Destructor Documentation
GameManager()
GameManager::GameManager (sf::Vector2u windowSize)
Definition at line 23 of file GameTypes.cpp.
References applyButtonLocker, applyResolutionButton, backButton, colorBlindModeButton, controlsButton, controlsConfig, displayModeButton, duoButton, errorServer, font, fps30Button, fps60Button, fpsDisplay, graphicsQualityButton, insertCoinText, launch, leftButtonSelection, ControlsConfig::loadResources(), ErrorServer::loadResources(), Launch::loadResources(), Parameters::loadResources(), Player::loadResources(), lockerButton, modeButton, numberPlayerToWait, paramButton, parameters, particleSystem, playButton, player, resolutionButton, rightButtonSelection, Button::setCharacterSize(), ParamButton::setCharacterSize(), ParticleSystem::setParameters(), ParamButton::setupVolumeBar(), soloButton, squadButton, statusText, and trioButton.
~GameManager()
GameManager::~GameManager () default
Member Function Documentation
addWaitingPlayer()
void GameManager::addWaitingPlayer () inline
Definition at line 132 of file GameTypes.hpp.
References waitingPlayersCounter.
applyCurrentResolution()
void GameManager::applyCurrentResolution (sf::RenderWindow & window)
Definition at line 758 of file GameTypes.cpp.
References currentFps, Parameters::getCurrentDisplayMode(), Parameters::getCurrentResolution(), Parameters::getResolutionSize(), handleWindowResize(), parameters, and WINDOWED.
Referenced by handleMouseClick().
connectToServer()
bool GameManager::connectToServer (const std::string & serverIP, unsigned short port) private
Definition at line 580 of file GameTypes.cpp.
connectToServerWithRooms()
void GameManager::connectToServerWithRooms (const std::string & serverIP, unsigned short port)
Definition at line 931 of file GameTypes.cpp.
References CONNECT, currentState, DISCONNECT, ERRORSERVER, initializeNetworking(), isConnected, networkClient, playerName, and statusText.
Referenced by handleMouseClick().
createRoom()
void GameManager::createRoom (const std::string & roomName, uint8_t maxPlayers = 4)
Definition at line 947 of file GameTypes.cpp.
References networkClient.
Referenced by onRoomList().
cycleColorBlindMode()
void GameManager::cycleColorBlindMode ()
Definition at line 729 of file GameTypes.cpp.
References DEUTERANOPIA, Parameters::getCurrentColorBlindMode(), MONOCHROME, NORMAL, parameters, PROTANOPIA, Parameters::setColorBlindMode(), and TRITANOPIA.
Referenced by handleMouseClick().
cycleDisplayMode()
void GameManager::cycleDisplayMode (sf::RenderWindow & window)
Definition at line 659 of file GameTypes.cpp.
References currentFps, FULLSCREEN, Parameters::getCurrentDisplayMode(), parameters, Parameters::setDisplayMode(), and WINDOWED.
Referenced by handleMouseClick().
cycleGraphicsQuality()
void GameManager::cycleGraphicsQuality ()
Definition at line 689 of file GameTypes.cpp.
References Parameters::getCurrentGraphicsQuality(), HIGH, LOW, MEDIUM, parameters, particleSystem, Parameters::setGraphicsQuality(), ParticleSystem::setMaxParticles(), and ULTRA.
Referenced by handleMouseClick().
cycleResolution()
void GameManager::cycleResolution ()
Definition at line 636 of file GameTypes.cpp.
References Parameters::getCurrentResolution(), parameters, RES_1280x720, RES_1920x1080, RES_800x600, and Parameters::setResolution().
Referenced by handleMouseClick().
gameDemo()
void GameManager::gameDemo (sf::RenderWindow & window)
Definition at line 778 of file GameTypes.cpp.
References Engine::DOWN, font, Engine::LEFT, Engine::PLAYER_INPUT, Engine::RIGHT, Engine::Event::setParam(), Engine::SHOOT, Engine::UP, Engine::Systems::PhysicsSystem::update(), and Engine::Systems::RenderSystem::update().
Referenced by render().
getCurrentFps()
int GameManager::getCurrentFps () const inline
Definition at line 137 of file GameTypes.hpp.
References currentFps.
getCurrentState()
State GameManager::getCurrentState () const inline
Definition at line 136 of file GameTypes.hpp.
References currentState.
getWaitingPlayersCount()
int GameManager::getWaitingPlayersCount () const inline
Definition at line 134 of file GameTypes.hpp.
References waitingPlayersCounter.
Referenced by handleMouseClick().
handleEvents()
void GameManager::handleEvents (sf::RenderWindow & window)
Definition at line 169 of file GameTypes.cpp.
References backButton, CONTROLS, controlsConfig, currentState, errorServer, fps30Button, fps60Button, ControlsConfig::handleEvent(), ErrorServer::handleEvent(), Launch::handleEvent(), Lobby::handleEvent(), Player::handleEvent(), handleKeyPress(), handleMouseClick(), handleMouseMove(), handleWindowResize(), isDraggingVolume, launch, lobby, paramButton, player, QUIT, Button::setHovered(), and ParamButton::setHovered().
Referenced by main().
handleKeyPress()
void GameManager::handleKeyPress (sf::Event & event, sf::RenderWindow & window) private
Definition at line 317 of file GameTypes.cpp.
References currentState, MENU, QUIT, SETTINGS, statusText, and updateStatusTextPosition().
Referenced by handleEvents().
handleMouseClick()
void GameManager::handleMouseClick (sf::Event & event, sf::RenderWindow & window) private
Definition at line 336 of file GameTypes.cpp.
References applyButtonLocker, applyCurrentResolution(), applyResolutionButton, availableRooms, backButton, colorBlindModeButton, CONNECT, connectToServerWithRooms(), CONTROLS, controlsButton, currentFps, currentState, cycleColorBlindMode(), cycleDisplayMode(), cycleGraphicsQuality(), cycleResolution(), DISCONNECT, displayModeButton, DUO, duoButton, ERRORSERVER, fps30Button, fps60Button, gameMode, getWaitingPlayersCount(), graphicsQualityButton, IN_ROOM, initializeNetworking(), insertCoinText, isChooseMode, Button::isClicked(), ParamButton::isClicked(), isConnected, isDraggingVolume, ParamButton::isVolumeBarClicked(), joinRoom(), LAUNCH, leftButtonSelection, LOBBY, LOCKER, lockerButton, MENU, modeButton, networkClient, numberPlayerToWait, paramButton, playButton, player, refreshRoomList(), resolutionButton, rightButtonSelection, ROOM_LIST, SETTINGS, ParamButton::setVolumeFromMouse(), SOLO, soloButton, SQUAD, squadButton, Player::starshipRect, Player::starshipSprite, statusText, TRIO, trioButton, updateStatusTextPosition(), waitingRoomAction, waitingRoomMaxPlayers, and waitingRoomName.
Referenced by handleEvents().
handleMouseMove()
void GameManager::handleMouseMove (sf::RenderWindow & window) private
Definition at line 495 of file GameTypes.cpp.
References applyButtonLocker, backButton, CONTROLS, currentState, duoButton, ERRORSERVER, fps30Button, fps60Button, isChooseMode, Button::isClicked(), ParamButton::isClicked(), isDraggingVolume, leftButtonSelection, LOBBY, LOCKER, lockerButton, MENU, modeButton, paramButton, playButton, rightButtonSelection, Button::setHovered(), ParamButton::setHovered(), SETTINGS, ParamButton::setVolumeFromMouse(), soloButton, squadButton, and trioButton.
Referenced by handleEvents().
handleWindowResize()
void GameManager::handleWindowResize (sf::Event & event) private
Definition at line 531 of file GameTypes.cpp.
References applyResolutionButton, colorBlindModeButton, currentState, displayModeButton, ERRORSERVER, errorServer, graphicsQualityButton, LAUNCH, launch, LOBBY, MENU, paramButton, particleSystem, player, resolutionButton, SETTINGS, ParamButton::setupVolumeBar(), Button::updatePositionAndSize(), updatePositions(), updateStatusTextPosition(), ErrorServer::updateWindowSize(), Launch::updateWindowSize(), ParticleSystem::updateWindowSize(), and Player::updateWindowSize().
Referenced by applyCurrentResolution(), and handleEvents().
initializeNetworking()
void GameManager::initializeNetworking (const std::string & playerName)
Definition at line 897 of file GameTypes.cpp.
References networkClient, onConnected(), onRoomCreated(), onRoomError(), onRoomJoined(), onRoomLeft(), onRoomList(), onRoomMessage(), and playerName.
Referenced by connectToServerWithRooms(), and handleMouseClick().
joinRoom()
void GameManager::joinRoom (const std::string & roomName)
Definition at line 954 of file GameTypes.cpp.
References networkClient.
Referenced by handleMouseClick(), and onRoomList().
leaveRoom()
void GameManager::leaveRoom ()
Definition at line 961 of file GameTypes.cpp.
References networkClient.
onConnected()
void GameManager::onConnected (uint32_t playerId) private
Definition at line 982 of file GameTypes.cpp.
References CONNECT, isConnected, refreshRoomList(), and statusText.
Referenced by initializeNetworking().
onRoomCreated()
void GameManager::onRoomCreated (const RtypeServer::RoomCreatedBody & body) private
Definition at line 990 of file GameTypes.cpp.
References currentRoomName, inRoom, RtypeServer::RoomCreatedBody::roomName, statusText, and RtypeServer::RoomCreatedBody::success.
Referenced by initializeNetworking().
onRoomError()
void GameManager::onRoomError (const RtypeServer::RoomErrorBody & body) private
Definition at line 1072 of file GameTypes.cpp.
References RtypeServer::RoomErrorBody::errorMessage, and statusText.
Referenced by initializeNetworking().
onRoomJoined()
void GameManager::onRoomJoined (const RtypeServer::RoomJoinedBody & body) private
Definition at line 1003 of file GameTypes.cpp.
References currentRoomName, gameMode, getMaxPlayersForMode(), inRoom, numberPlayerToWait, RtypeServer::RoomJoinedBody::playerCount, refreshRoomList(), RtypeServer::RoomJoinedBody::roomName, statusText, and RtypeServer::RoomJoinedBody::success.
Referenced by initializeNetworking().
onRoomLeft()
void GameManager::onRoomLeft (const RtypeServer::RoomLeftBody & body) private
Definition at line 1021 of file GameTypes.cpp.
References currentRoomName, inRoom, numberPlayerToWait, refreshRoomList(), statusText, and RtypeServer::RoomLeftBody::success.
Referenced by initializeNetworking().
onRoomList()
void GameManager::onRoomList (const RtypeServer::RoomListBody & body) private
Definition at line 1037 of file GameTypes.cpp.
References availableRooms, createRoom(), currentRoomName, currentState, gameMode, getMaxPlayersForMode(), joinRoom(), LOBBY, numberPlayerToWait, RtypeServer::RoomListBody::rooms, waitingRoomAction, waitingRoomMaxPlayers, and waitingRoomName.
Referenced by initializeNetworking().
onRoomMessage()
void GameManager::onRoomMessage (const RtypeServer::RoomMessageBody & body) private
Definition at line 1067 of file GameTypes.cpp.
References RtypeServer::RoomMessageBody::message, and RtypeServer::RoomMessageBody::senderName.
Referenced by initializeNetworking().
refreshRoomList()
void GameManager::refreshRoomList ()
Definition at line 968 of file GameTypes.cpp.
References networkClient.
Referenced by handleMouseClick(), onConnected(), onRoomJoined(), and onRoomLeft().
removeWaitingPlayer()
void GameManager::removeWaitingPlayer () inline
Definition at line 133 of file GameTypes.hpp.
References waitingPlayersCounter.
render()
void GameManager::render (sf::RenderWindow & window)
Definition at line 238 of file GameTypes.cpp.
References applyButtonLocker, applyResolutionButton, backButton, colorBlindModeButton, CONNECT, CONTROLS, controlsButton, controlsConfig, currentState, DISCONNECT, displayModeButton, Button::draw(), ControlsConfig::draw(), ErrorServer::draw(), Launch::draw(), ParamButton::draw(), Parameters::draw(), Player::draw(), ParamButton::drawVolumeBar(), duoButton, ERRORSERVER, errorServer, fps30Button, fps60Button, fpsDisplay, GAME, gameDemo(), graphicsQualityButton, IN_ROOM, insertCoinText, isChooseMode, isConnected, LAUNCH, launch, leftButtonSelection, LOBBY, LOCKER, lockerButton, MENU, modeButton, numberPlayerToWait, paramButton, parameters, particleSystem, playButton, player, QUIT, ParticleSystem::render(), resolutionButton, rightButtonSelection, ROOM_LIST, SETTINGS, soloButton, squadButton, statusText, trioButton, and ParamButton::updatePositionAndSize().
Referenced by main().
renderInRoom()
void GameManager::renderInRoom (sf::RenderWindow & window) private
renderRoomList()
void GameManager::renderRoomList (sf::RenderWindow & window) private
sendRoomMessage()
void GameManager::sendRoomMessage (const std::string & message)
Definition at line 975 of file GameTypes.cpp.
References networkClient.
shouldClose()
bool GameManager::shouldClose () const
Definition at line 312 of file GameTypes.cpp.
References currentState, and QUIT.
Referenced by main().
update()
void GameManager::update ()
Definition at line 210 of file GameTypes.cpp.
References currentFps, currentState, deltaClock, DUO, ERRORSERVER, errorServer, fpsDisplay, GAME, gameMode, insertCoinClock, insertCoinText, LAUNCH, launch, LOBBY, LOCKER, MENU, particleSystem, player, SOLO, SQUAD, TRIO, ErrorServer::update(), Launch::update(), ParticleSystem::update(), Player::update(), and waitingPlayersCounter.
Referenced by main().
updatePositions()
void GameManager::updatePositions (sf::Vector2u windowSize)
Definition at line 127 of file GameTypes.cpp.
References applyButtonLocker, applyResolutionButton, backButton, colorBlindModeButton, controlsButton, displayModeButton, duoButton, fps30Button, fps60Button, graphicsQualityButton, insertCoinText, leftButtonSelection, lockerButton, modeButton, numberPlayerToWait, paramButton, playButton, resolutionButton, rightButtonSelection, soloButton, squadButton, trioButton, Button::updatePositionAndSize(), and ParamButton::updatePositionAndSize().
Referenced by handleWindowResize().
updateStatusTextPosition()
void GameManager::updateStatusTextPosition (bool isParametersMode = false) private
Definition at line 568 of file GameTypes.cpp.
References statusText.
Referenced by handleKeyPress(), handleMouseClick(), and handleWindowResize().
Member Data Documentation
applyButtonLocker
Button GameManager::applyButtonLocker private
Definition at line 76 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
applyResolutionButton
Button GameManager::applyResolutionButton private
Definition at line 70 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleWindowResize(), render(), and updatePositions().
availableRooms
std::vector<RtypeServer::RoomInfoEntry> GameManager::availableRooms private
Definition at line 102 of file GameTypes.hpp.
Referenced by handleMouseClick(), and onRoomList().
backButton
Button GameManager::backButton private
Definition at line 65 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
colorBlindModeButton
Button GameManager::colorBlindModeButton private
Definition at line 69 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleWindowResize(), render(), and updatePositions().
controlsButton
Button GameManager::controlsButton private
Definition at line 71 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), render(), and updatePositions().
controlsConfig
ControlsConfig GameManager::controlsConfig private
Definition at line 57 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), and render().
currentFps
int GameManager::currentFps private
Definition at line 114 of file GameTypes.hpp.
Referenced by applyCurrentResolution(), cycleDisplayMode(), getCurrentFps(), handleMouseClick(), and update().
currentRoomName
std::string GameManager::currentRoomName private
Definition at line 103 of file GameTypes.hpp.
Referenced by onRoomCreated(), onRoomJoined(), onRoomLeft(), and onRoomList().
currentState
State GameManager::currentState private
Definition at line 109 of file GameTypes.hpp.
Referenced by connectToServerWithRooms(), getCurrentState(), handleEvents(), handleKeyPress(), handleMouseClick(), handleMouseMove(), handleWindowResize(), onRoomList(), render(), shouldClose(), and update().
deltaClock
sf::Clock GameManager::deltaClock private
Definition at line 98 of file GameTypes.hpp.
Referenced by update().
displayModeButton
Button GameManager::displayModeButton private
Definition at line 67 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleWindowResize(), render(), and updatePositions().
duoButton
Button GameManager::duoButton private
Definition at line 79 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
errorServer
ErrorServer GameManager::errorServer private
Definition at line 60 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), handleWindowResize(), render(), and update().
font
sf::Font GameManager::font private
Definition at line 92 of file GameTypes.hpp.
Referenced by gameDemo(), and GameManager().
fps30Button
ParamButton GameManager::fps30Button private
Definition at line 63 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
fps60Button
ParamButton GameManager::fps60Button private
Definition at line 64 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
fpsDisplay
sf::Text GameManager::fpsDisplay private
Definition at line 91 of file GameTypes.hpp.
Referenced by GameManager(), render(), and update().
gameMode
GameMode GameManager::gameMode private
Definition at line 88 of file GameTypes.hpp.
Referenced by handleMouseClick(), onRoomJoined(), onRoomList(), and update().
graphicsQualityButton
Button GameManager::graphicsQualityButton private
Definition at line 68 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleWindowResize(), render(), and updatePositions().
inRoom
bool GameManager::inRoom private
Definition at line 104 of file GameTypes.hpp.
Referenced by onRoomCreated(), onRoomJoined(), and onRoomLeft().
insertCoinClock
sf::Clock GameManager::insertCoinClock private
Definition at line 95 of file GameTypes.hpp.
Referenced by update().
insertCoinText
sf::Text GameManager::insertCoinText private
Definition at line 94 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), render(), update(), and updatePositions().
isChooseMode
bool GameManager::isChooseMode private
Definition at line 112 of file GameTypes.hpp.
Referenced by handleMouseClick(), handleMouseMove(), and render().
isConfiguringControls
bool GameManager::isConfiguringControls private
Definition at line 113 of file GameTypes.hpp.
isConnected
ServerState GameManager::isConnected private
Definition at line 110 of file GameTypes.hpp.
Referenced by connectToServerWithRooms(), handleMouseClick(), onConnected(), and render().
isDraggingVolume
bool GameManager::isDraggingVolume private
Definition at line 111 of file GameTypes.hpp.
Referenced by handleEvents(), handleMouseClick(), and handleMouseMove().
launch
Launch GameManager::launch private
Definition at line 55 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), handleWindowResize(), render(), and update().
leftButtonSelection
Button GameManager::leftButtonSelection private
Definition at line 74 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
lobby
Lobby GameManager::lobby private
Definition at line 58 of file GameTypes.hpp.
Referenced by handleEvents().
lockerButton
Button GameManager::lockerButton private
Definition at line 73 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
modeButton
Button GameManager::modeButton private
Definition at line 82 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
networkClient
std::unique_ptr<NetworkClient> GameManager::networkClient private
Definition at line 100 of file GameTypes.hpp.
Referenced by connectToServerWithRooms(), createRoom(), handleMouseClick(), initializeNetworking(), joinRoom(), leaveRoom(), refreshRoomList(), and sendRoomMessage().
numberPlayerToWait
sf::Text GameManager::numberPlayerToWait private
Definition at line 85 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), onRoomJoined(), onRoomLeft(), onRoomList(), render(), and updatePositions().
paramButton
ParamButton GameManager::paramButton private
Definition at line 62 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), handleMouseClick(), handleMouseMove(), handleWindowResize(), render(), and updatePositions().
parameters
Parameters GameManager::parameters private
Definition at line 56 of file GameTypes.hpp.
Referenced by applyCurrentResolution(), cycleColorBlindMode(), cycleDisplayMode(), cycleGraphicsQuality(), cycleResolution(), GameManager(), and render().
particleSystem
ParticleSystem GameManager::particleSystem private
Definition at line 97 of file GameTypes.hpp.
Referenced by cycleGraphicsQuality(), GameManager(), handleWindowResize(), render(), and update().
playButton
Button GameManager::playButton private
Definition at line 83 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
player
Player GameManager::player private
Definition at line 61 of file GameTypes.hpp.
Referenced by GameManager(), handleEvents(), handleMouseClick(), handleWindowResize(), render(), and update().
playerName
std::string GameManager::playerName private
Definition at line 101 of file GameTypes.hpp.
Referenced by connectToServerWithRooms(), and initializeNetworking().
resolutionButton
Button GameManager::resolutionButton private
Definition at line 66 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleWindowResize(), render(), and updatePositions().
rightButtonSelection
Button GameManager::rightButtonSelection private
Definition at line 75 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
soloButton
Button GameManager::soloButton private
Definition at line 78 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
squadButton
Button GameManager::squadButton private
Definition at line 81 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
statusText
sf::Text GameManager::statusText private
Definition at line 90 of file GameTypes.hpp.
Referenced by connectToServerWithRooms(), GameManager(), handleKeyPress(), handleMouseClick(), onConnected(), onRoomCreated(), onRoomError(), onRoomJoined(), onRoomLeft(), render(), and updateStatusTextPosition().
trioButton
Button GameManager::trioButton private
Definition at line 80 of file GameTypes.hpp.
Referenced by GameManager(), handleMouseClick(), handleMouseMove(), render(), and updatePositions().
waitingPlayersCounter
int GameManager::waitingPlayersCounter private
Definition at line 86 of file GameTypes.hpp.
Referenced by addWaitingPlayer(), getWaitingPlayersCount(), removeWaitingPlayer(), and update().
waitingRoomAction
bool GameManager::waitingRoomAction = false private
Definition at line 105 of file GameTypes.hpp.
Referenced by handleMouseClick(), and onRoomList().
waitingRoomMaxPlayers
uint8_t GameManager::waitingRoomMaxPlayers = 1 private
Definition at line 107 of file GameTypes.hpp.
Referenced by handleMouseClick(), and onRoomList().
waitingRoomName
std::string GameManager::waitingRoomName private
Definition at line 106 of file GameTypes.hpp.
Referenced by handleMouseClick(), and onRoomList().
The documentation for this class was generated from the following files:
GameTypes.hpp
GameTypes.cpp