R-TYPE: Engine::NetworkManager Class Reference
Engine::NetworkManager Class Reference
#include <NetworkManager.hpp>
Classes
struct ComponentBody
struct EntityBody
struct EntityDestroyBody
struct HelloBody
struct InputBody
struct PacketHeader
struct WelcomeBody
Public Types
enum class Role { CLIENT , SERVER }
enum MsgType {
MSG_HELLO = 1 , MSG_WELCOME = 2 , MSG_PING = 3 , MSG_PONG = 4 ,
MSG_INPUT = 5 , MSG_ENTITY = 6 , MSG_ENTITY_DESTROYED = 7 , MSG_COMPONENT = 8
}
Public Member Functions
Role getRole ()
NetworkManager (Role role, const std::string &address="127.0.0.1", uint16_t port=8080)
~NetworkManager ()
void sendPacket (const void *data, size_t size)
void receivePacket ()
void startServer ()
PacketHeader createPacketHeader (MsgType type, uint32_t seq=0, uint32_t ack=0, uint32_t ack_bits=0)
void sendHello (const std::string &client_name, uint32_t nonce)
void sendWelcome ()
void sendPong (uint32_t seq)
void sendPing (uint32_t seq)
void handleTimeouts ()
template<std::size_t S>
void sendInput (const uint32_t player_id, const uint16_t room_id, const std::bitset< S > inputs)
void sendEntity (const Entity &entity, const Signature &signature)
template<typename T >
void sendComponent (const Entity &entity, const T &component)
void sendDestroyEntity (const Entity &entity)
void receiveWelcome ()
void receiveInputs ()
void receiveEntity ()
void receiveComponent ()
void receiveDestroyEntity ()
void start_receive ()
int getConnectedPlayers ()
Public Attributes
const uint16_t MAGIC = 0xCAFE
const uint8_t PROTO_VERSION = 1
std::shared_ptr< Engine::Mediator > mediator
uint32_t player_id
uint16_t room_id
Private Member Functions
void handle_receive (std::size_t bytes_recvd)
template<typename ComponentType >
void registerComponent ()
Private Attributes
Role role
std::string address
uint16_t port
boost::asio::io_context io_context
boost::asio::ip::udp::socket socket
boost::asio::ip::udp::endpoint remote_endpoint
std::array< uint8_t, 1024 > recv_buffer
std::thread io_thread
std::unordered_map< std::size_t, boost::asio::ip::udp::endpoint > client_endpoints {}
boost::asio::ip::udp::endpoint temp_sender_endpoint
std::unordered_map< boost::asio::ip::udp::endpoint, std::chrono::time_point< std::chrono::steady_clock > > client_timeout_clocks {}
ComponentRegistry componentRegistry
Detailed Description
Definition at line 24 of file NetworkManager.hpp.
Member Enumeration Documentation
MsgType
enum Engine::NetworkManager::MsgType
Enumerator
MSG_HELLO
MSG_WELCOME
MSG_PING
MSG_PONG
MSG_INPUT
MSG_ENTITY
MSG_ENTITY_DESTROYED
MSG_COMPONENT
Definition at line 33 of file NetworkManager.hpp.
Role
enum class Engine::NetworkManager::Role strong
Enumerator
CLIENT
SERVER
Definition at line 26 of file NetworkManager.hpp.
Constructor & Destructor Documentation
NetworkManager()
Engine::NetworkManager::NetworkManager (Role role, const std::string & address = "127.0.0.1", uint16_t port = 8080)
Definition at line 30 of file NetworkManager.cpp.
References address, io_context, io_thread, mediator, port, registerComponent(), remote_endpoint, role, SERVER, socket, and start_receive().
~NetworkManager()
Engine::NetworkManager::~NetworkManager ()
Definition at line 400 of file NetworkManager.cpp.
Member Function Documentation
createPacketHeader()
Engine::NetworkManager::PacketHeader Engine::NetworkManager::createPacketHeader (MsgType type, uint32_t seq = 0, uint32_t ack = 0, uint32_t ack_bits = 0)
Definition at line 194 of file NetworkManager.cpp.
References Engine::NetworkManager::PacketHeader::ack, Engine::NetworkManager::PacketHeader::ack_bits, Engine::NetworkManager::PacketHeader::magic, Engine::NetworkManager::PacketHeader::seq, Engine::NetworkManager::PacketHeader::type, and Engine::NetworkManager::PacketHeader::version.
Referenced by sendInput().
getConnectedPlayers()
int Engine::NetworkManager::getConnectedPlayers ()
Definition at line 407 of file NetworkManager.cpp.
getRole()
Engine::NetworkManager::Role Engine::NetworkManager::getRole ()
Definition at line 189 of file NetworkManager.cpp.
handle_receive()
void Engine::NetworkManager::handle_receive (std::size_t bytes_recvd) private
Definition at line 97 of file NetworkManager.cpp.
References Engine::NetworkManager::PacketHeader::ack, Engine::NetworkManager::PacketHeader::ack_bits, Engine::NetworkManager::PacketHeader::magic, Engine::NetworkManager::PacketHeader::seq, Engine::NetworkManager::PacketHeader::type, and Engine::NetworkManager::PacketHeader::version.
handleTimeouts()
void Engine::NetworkManager::handleTimeouts ()
Definition at line 159 of file NetworkManager.cpp.
receiveComponent()
void Engine::NetworkManager::receiveComponent ()
Definition at line 381 of file NetworkManager.cpp.
References Engine::NetworkManager::ComponentBody::component_len, Engine::NetworkManager::ComponentBody::entity_id, and Engine::NetworkManager::ComponentBody::name_len.
receiveDestroyEntity()
void Engine::NetworkManager::receiveDestroyEntity ()
Definition at line 367 of file NetworkManager.cpp.
References Engine::NetworkManager::EntityDestroyBody::entity_id.
receiveEntity()
void Engine::NetworkManager::receiveEntity ()
Definition at line 352 of file NetworkManager.cpp.
References Engine::NetworkManager::EntityBody::entity_id, and Engine::NetworkManager::EntityBody::signature.
receiveInputs()
void Engine::NetworkManager::receiveInputs ()
Definition at line 339 of file NetworkManager.cpp.
References Engine::NetworkManager::InputBody::input_data, Engine::NetworkManager::InputBody::player_id, Engine::PLAYER_INPUT, and Engine::Event::setParam().
receivePacket()
void Engine::NetworkManager::receivePacket ()
Definition at line 66 of file NetworkManager.cpp.
receiveWelcome()
void Engine::NetworkManager::receiveWelcome ()
Definition at line 321 of file NetworkManager.cpp.
References Engine::NetworkManager::WelcomeBody::baseline_tick, Engine::NetworkManager::WelcomeBody::player_id, and Engine::NetworkManager::WelcomeBody::room_id.
registerComponent()
template<typename ComponentType > void Engine::NetworkManager::registerComponent () private
Definition at line 162 of file NetworkManager.hpp.
References Engine::Mediator::addComponent().
Referenced by NetworkManager().
sendComponent()
template<typename T > void Engine::NetworkManager::sendComponent (const Entity & entity, const T & component)
Definition at line 174 of file NetworkManager.hpp.
References Engine::NetworkManager::ComponentBody::name_len.
sendDestroyEntity()
void Engine::NetworkManager::sendDestroyEntity (const Entity & entity)
Definition at line 301 of file NetworkManager.cpp.
sendEntity()
void Engine::NetworkManager::sendEntity (const Entity & entity, const Signature & signature)
Definition at line 280 of file NetworkManager.cpp.
sendHello()
void Engine::NetworkManager::sendHello (const std::string & client_name, uint32_t nonce)
Definition at line 207 of file NetworkManager.cpp.
sendInput()
template<std::size_t S> void Engine::NetworkManager::sendInput (const uint32_t player_id, const uint16_t room_id, const std::bitset< S > inputs)
Definition at line 146 of file NetworkManager.hpp.
References createPacketHeader(), MSG_INPUT, player_id, remote_endpoint, room_id, and socket.
sendPacket()
void Engine::NetworkManager::sendPacket (const void * data, size_t size)
Definition at line 59 of file NetworkManager.cpp.
sendPing()
void Engine::NetworkManager::sendPing (uint32_t seq)
Definition at line 272 of file NetworkManager.cpp.
sendPong()
void Engine::NetworkManager::sendPong (uint32_t seq)
Definition at line 264 of file NetworkManager.cpp.
sendWelcome()
void Engine::NetworkManager::sendWelcome ()
Definition at line 231 of file NetworkManager.cpp.
References Engine::NetworkManager::HelloBody::name_len, Engine::NetworkManager::HelloBody::nonce, Engine::NetworkManager::WelcomeBody::player_id, and Engine::NetworkManager::HelloBody::version.
start_receive()
void Engine::NetworkManager::start_receive ()
Definition at line 81 of file NetworkManager.cpp.
Referenced by NetworkManager().
startServer()
void Engine::NetworkManager::startServer ()
Definition at line 74 of file NetworkManager.cpp.
Member Data Documentation
address
std::string Engine::NetworkManager::address private
Definition at line 128 of file NetworkManager.hpp.
Referenced by NetworkManager().
client_endpoints
std::unordered_map<std::size_t, boost::asio::ip::udp::endpoint> Engine::NetworkManager::client_endpoints {} private
Definition at line 136 of file NetworkManager.hpp.
client_timeout_clocks
std::unordered_map<boost::asio::ip::udp::endpoint, std::chrono::time_point<std::chrono::steady_clock> > Engine::NetworkManager::client_timeout_clocks {} private
Definition at line 138 of file NetworkManager.hpp.
componentRegistry
ComponentRegistry Engine::NetworkManager::componentRegistry private
Definition at line 140 of file NetworkManager.hpp.
io_context
boost::asio::io_context Engine::NetworkManager::io_context private
Definition at line 130 of file NetworkManager.hpp.
Referenced by NetworkManager().
io_thread
std::thread Engine::NetworkManager::io_thread private
Definition at line 134 of file NetworkManager.hpp.
Referenced by NetworkManager().
MAGIC
const uint16_t Engine::NetworkManager::MAGIC = 0xCAFE
Definition at line 44 of file NetworkManager.hpp.
mediator
std::shared_ptr<Engine::Mediator> Engine::NetworkManager::mediator
Definition at line 118 of file NetworkManager.hpp.
Referenced by NetworkManager().
player_id
uint32_t Engine::NetworkManager::player_id
Definition at line 120 of file NetworkManager.hpp.
Referenced by sendInput().
port
uint16_t Engine::NetworkManager::port private
Definition at line 129 of file NetworkManager.hpp.
Referenced by NetworkManager().
PROTO_VERSION
const uint8_t Engine::NetworkManager::PROTO_VERSION = 1
Definition at line 45 of file NetworkManager.hpp.
recv_buffer
std::array<uint8_t, 1024> Engine::NetworkManager::recv_buffer private
Definition at line 133 of file NetworkManager.hpp.
remote_endpoint
boost::asio::ip::udp::endpoint Engine::NetworkManager::remote_endpoint private
Definition at line 132 of file NetworkManager.hpp.
Referenced by NetworkManager(), and sendInput().
role
Role Engine::NetworkManager::role private
Definition at line 127 of file NetworkManager.hpp.
Referenced by NetworkManager().
room_id
uint16_t Engine::NetworkManager::room_id
Definition at line 121 of file NetworkManager.hpp.
Referenced by sendInput().
socket
boost::asio::ip::udp::socket Engine::NetworkManager::socket private
Definition at line 131 of file NetworkManager.hpp.
Referenced by NetworkManager(), and sendInput().
temp_sender_endpoint
boost::asio::ip::udp::endpoint Engine::NetworkManager::temp_sender_endpoint private
Definition at line 137 of file NetworkManager.hpp.
The documentation for this class was generated from the following files:
NetworkManager.hpp
NetworkManager.cpp