R-TYPE: Player Class Reference
Player Class Reference
#include <Player.hpp>
Public Member Functions
Player (sf::Vector2u windowSize)
~Player ()=default
bool loadResources ()
void draw (sf::RenderWindow &window)
void handleEvent (const sf::Event &event, sf::RenderWindow &window)
void update ()
void updateWindowSize (sf::Vector2u newSize)
void updateAnimationStarship ()
Public Attributes
sf::IntRect starshipRect
sf::Sprite starshipSprite
Private Member Functions
void centerImage ()
Private Attributes
sf::Texture starshipTexture
sf::Vector2u windowSize
sf::Clock starshipClock
int starshipCounter = 0
Detailed Description
Definition at line 14 of file Player.hpp.
Constructor & Destructor Documentation
Player()
Player::Player (sf::Vector2u windowSize)
Definition at line 11 of file Player.cpp.
~Player()
Player::~Player () default
Member Function Documentation
centerImage()
void Player::centerImage () private
Definition at line 31 of file Player.cpp.
References starshipSprite, and windowSize.
Referenced by handleEvent(), loadResources(), and updateWindowSize().
draw()
void Player::draw (sf::RenderWindow & window)
Definition at line 42 of file Player.cpp.
References starshipSprite.
Referenced by GameManager::render().
handleEvent()
void Player::handleEvent (const sf::Event & event, sf::RenderWindow & window)
Definition at line 47 of file Player.cpp.
References centerImage(), and windowSize.
Referenced by GameManager::handleEvents().
loadResources()
bool Player::loadResources ()
Definition at line 15 of file Player.cpp.
References centerImage(), starshipRect, starshipSprite, and starshipTexture.
Referenced by GameManager::GameManager().
update()
void Player::update ()
Definition at line 62 of file Player.cpp.
References updateAnimationStarship().
Referenced by GameManager::update().
updateAnimationStarship()
void Player::updateAnimationStarship ()
Definition at line 67 of file Player.cpp.
References starshipClock, starshipCounter, starshipRect, starshipSprite, and starshipTexture.
Referenced by update().
updateWindowSize()
void Player::updateWindowSize (sf::Vector2u newSize)
Definition at line 93 of file Player.cpp.
References centerImage(), and windowSize.
Referenced by GameManager::handleWindowResize().
Member Data Documentation
starshipClock
sf::Clock Player::starshipClock private
Definition at line 32 of file Player.hpp.
Referenced by updateAnimationStarship().
starshipCounter
int Player::starshipCounter = 0 private
Definition at line 33 of file Player.hpp.
Referenced by updateAnimationStarship().
starshipRect
sf::IntRect Player::starshipRect
Definition at line 25 of file Player.hpp.
Referenced by GameManager::handleMouseClick(), loadResources(), and updateAnimationStarship().
starshipSprite
sf::Sprite Player::starshipSprite
Definition at line 26 of file Player.hpp.
Referenced by centerImage(), draw(), GameManager::handleMouseClick(), loadResources(), and updateAnimationStarship().
starshipTexture
sf::Texture Player::starshipTexture private
Definition at line 29 of file Player.hpp.
Referenced by loadResources(), and updateAnimationStarship().
windowSize
sf::Vector2u Player::windowSize private
Definition at line 30 of file Player.hpp.
Referenced by centerImage(), handleEvent(), and updateWindowSize().
The documentation for this class was generated from the following files:
Player.hpp
Player.cpp