R-TYPE: ParticleSystem Class Reference
ParticleSystem Class Reference
#include <ParticleSystem.hpp>
Public Member Functions
ParticleSystem (Engine::Utils::Vec2UInt winSize, int maxPart=500)
~ParticleSystem ()=default
void update (float deltaTime)
void render (sf::RenderWindow &window)
void updateWindowSize (Engine::Utils::Vec2UInt newSize)
void setMaxParticles (int maxPart)
void setParameters (const Parameters *params)
Private Member Functions
void spawnParticle (ParticleType type)
void updateParticle (Particle &particle, float deltaTime)
void renderParticle (sf::RenderWindow &window, const Particle &particle)
sf::Color getRandomColor (ParticleType type)
sf::Vector2f getRandomPosition ()
sf::Vector2f getRandomVelocity (ParticleType type)
float getRandomSize (ParticleType type)
float getRandomLife (ParticleType type)
Private Attributes
std::vector< Particle > particles
Engine::Utils::Vec2UInt windowSize
std::mt19937 generator
std::uniform_real_distribution< float > distribution
int maxParticles
float spawnRate
float spawnTimer
std::vector< sf::Color > starColors
std::vector< sf::Color > dustColors
std::vector< sf::Color > nebulaColors
const Parameters * parameters
Detailed Description
Definition at line 49 of file ParticleSystem.hpp.
Constructor & Destructor Documentation
ParticleSystem()
ParticleSystem::ParticleSystem (Engine::Utils::Vec2UInt winSize, int maxPart = 500)
Definition at line 15 of file ParticleSystem.cpp.
References distribution, DUST, dustColors, generator, maxParticles, NEBULA, nebulaColors, particles, spawnParticle(), STAR, and starColors.
~ParticleSystem()
ParticleSystem::~ParticleSystem () default
Member Function Documentation
getRandomColor()
sf::Color ParticleSystem::getRandomColor (ParticleType type) private
Definition at line 217 of file ParticleSystem.cpp.
References distribution, DUST, dustColors, generator, NEBULA, nebulaColors, SHOOTING_STAR, STAR, and starColors.
Referenced by spawnParticle().
getRandomLife()
float ParticleSystem::getRandomLife (ParticleType type) private
Definition at line 282 of file ParticleSystem.cpp.
References distribution, DUST, generator, NEBULA, SHOOTING_STAR, and STAR.
Referenced by spawnParticle().
getRandomPosition()
sf::Vector2f ParticleSystem::getRandomPosition () private
Definition at line 233 of file ParticleSystem.cpp.
References distribution, generator, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by spawnParticle().
getRandomSize()
float ParticleSystem::getRandomSize (ParticleType type) private
Definition at line 266 of file ParticleSystem.cpp.
References distribution, DUST, generator, NEBULA, SHOOTING_STAR, and STAR.
Referenced by spawnParticle().
getRandomVelocity()
sf::Vector2f ParticleSystem::getRandomVelocity (ParticleType type) private
Definition at line 241 of file ParticleSystem.cpp.
References distribution, DUST, generator, NEBULA, SHOOTING_STAR, and STAR.
Referenced by spawnParticle().
render()
void ParticleSystem::render (sf::RenderWindow & window)
Definition at line 85 of file ParticleSystem.cpp.
References particles, and renderParticle().
Referenced by GameManager::render().
renderParticle()
void ParticleSystem::renderParticle (sf::RenderWindow & window, const Particle & particle) private
Definition at line 169 of file ParticleSystem.cpp.
References Parameters::applyColorBlindFilter(), Particle::color, parameters, Particle::position, Particle::rotation, SHOOTING_STAR, Particle::size, STAR, and Particle::type.
Referenced by render().
setMaxParticles()
void ParticleSystem::setMaxParticles (int maxPart)
Definition at line 298 of file ParticleSystem.cpp.
References maxParticles, and particles.
Referenced by GameManager::cycleGraphicsQuality().
setParameters()
void ParticleSystem::setParameters (const Parameters * params)
Definition at line 307 of file ParticleSystem.cpp.
References parameters.
Referenced by GameManager::GameManager().
spawnParticle()
void ParticleSystem::spawnParticle (ParticleType type) private
Definition at line 110 of file ParticleSystem.cpp.
References Particle::alpha, distribution, DUST, generator, getRandomColor(), getRandomLife(), getRandomPosition(), getRandomSize(), getRandomVelocity(), NEBULA, particles, Particle::position, Particle::rotationSpeed, Particle::scintillation, SHOOTING_STAR, STAR, Particle::velocity, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by ParticleSystem(), and update().
update()
void ParticleSystem::update (float deltaTime)
Definition at line 55 of file ParticleSystem.cpp.
References distribution, DUST, generator, maxParticles, NEBULA, particles, SHOOTING_STAR, spawnParticle(), spawnRate, spawnTimer, STAR, updateParticle(), windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by GameManager::update().
updateParticle()
void ParticleSystem::updateParticle (Particle & particle, float deltaTime) private
Definition at line 141 of file ParticleSystem.cpp.
References Particle::alpha, Particle::color, DUST, Particle::life, Particle::maxLife, NEBULA, Particle::position, Particle::rotation, Particle::rotationSpeed, Particle::scintillation, SHOOTING_STAR, Particle::size, STAR, Particle::type, and Particle::velocity.
Referenced by update().
updateWindowSize()
void ParticleSystem::updateWindowSize (Engine::Utils::Vec2UInt newSize)
Definition at line 92 of file ParticleSystem.cpp.
References particles, windowSize, Engine::Utils::Vec2UInt::x, and Engine::Utils::Vec2UInt::y.
Referenced by GameManager::handleWindowResize().
Member Data Documentation
distribution
std::uniform_real_distribution<float> ParticleSystem::distribution private
Definition at line 54 of file ParticleSystem.hpp.
Referenced by getRandomColor(), getRandomLife(), getRandomPosition(), getRandomSize(), getRandomVelocity(), ParticleSystem(), spawnParticle(), and update().
dustColors
std::vector<sf::Color> ParticleSystem::dustColors private
Definition at line 60 of file ParticleSystem.hpp.
Referenced by getRandomColor(), and ParticleSystem().
generator
std::mt19937 ParticleSystem::generator private
Definition at line 53 of file ParticleSystem.hpp.
Referenced by getRandomColor(), getRandomLife(), getRandomPosition(), getRandomSize(), getRandomVelocity(), ParticleSystem(), spawnParticle(), and update().
maxParticles
int ParticleSystem::maxParticles private
Definition at line 56 of file ParticleSystem.hpp.
Referenced by ParticleSystem(), setMaxParticles(), and update().
nebulaColors
std::vector<sf::Color> ParticleSystem::nebulaColors private
Definition at line 61 of file ParticleSystem.hpp.
Referenced by getRandomColor(), and ParticleSystem().
parameters
const Parameters* ParticleSystem::parameters private
Definition at line 63 of file ParticleSystem.hpp.
Referenced by renderParticle(), and setParameters().
particles
std::vector<Particle> ParticleSystem::particles private
Definition at line 51 of file ParticleSystem.hpp.
Referenced by ParticleSystem(), render(), setMaxParticles(), spawnParticle(), update(), and updateWindowSize().
spawnRate
float ParticleSystem::spawnRate private
Definition at line 57 of file ParticleSystem.hpp.
Referenced by update().
spawnTimer
float ParticleSystem::spawnTimer private
Definition at line 58 of file ParticleSystem.hpp.
Referenced by update().
starColors
std::vector<sf::Color> ParticleSystem::starColors private
Definition at line 59 of file ParticleSystem.hpp.
Referenced by getRandomColor(), and ParticleSystem().
windowSize
Engine::Utils::Vec2UInt ParticleSystem::windowSize private
Definition at line 52 of file ParticleSystem.hpp.
Referenced by getRandomPosition(), spawnParticle(), update(), and updateWindowSize().
The documentation for this class was generated from the following files:
ParticleSystem.hpp
ParticleSystem.cpp