R-TYPE: RtypeServer Namespace Reference
RtypeServer Namespace Reference
Classes
struct ClientSession
struct CreateRoomBody
struct HelloBody
struct JoinRoomBody
class Log
struct MessageBody
struct NetHeader
class Protocol
class Room
struct RoomCreatedBody
struct RoomErrorBody
struct RoomInfo
struct RoomInfoEntry
struct RoomJoinedBody
struct RoomLeftBody
struct RoomListBody
class RoomManager
struct RoomMessageBody
class UdpServer
struct WelcomeBody
Typedefs
using udp = boost::asio::ip::udp
Enumerations
enum class MsgType : uint8_t {
HELLO = 1 , WELCOME = 2 , PING = 3 , PONG = 4 ,
INPUT = 10 , SNAPSHOT = 11 , EVENT = 12 , CREATE_ROOM = 20 ,
JOIN_ROOM = 21 , LEAVE_ROOM = 22 , LIST_ROOMS = 23 , MESSAGE = 24 ,
ROOM_CREATED = 30 , ROOM_JOINED = 31 , ROOM_LEFT = 32 , ROOM_LIST = 33 ,
ROOM_MESSAGE = 34 , ROOM_ERROR = 35 , HELLO = 1 , WELCOME = 2 ,
PING = 3 , PONG = 4 , INPUT = 10 , SNAPSHOT = 11 ,
EVENT = 12 , CREATE_ROOM = 20 , JOIN_ROOM = 21 , LEAVE_ROOM = 22 ,
LIST_ROOMS = 23 , MESSAGE = 24 , ROOM_CREATED = 30 , ROOM_JOINED = 31 ,
ROOM_LEFT = 32 , ROOM_LIST = 33 , ROOM_MESSAGE = 34 , ROOM_ERROR = 35
}
enum LogLevel { DEBUG , INFO , WARNING , ERROR }
enum class MsgType : uint8_t {
HELLO = 1 , WELCOME = 2 , PING = 3 , PONG = 4 ,
INPUT = 10 , SNAPSHOT = 11 , EVENT = 12 , CREATE_ROOM = 20 ,
JOIN_ROOM = 21 , LEAVE_ROOM = 22 , LIST_ROOMS = 23 , MESSAGE = 24 ,
ROOM_CREATED = 30 , ROOM_JOINED = 31 , ROOM_LEFT = 32 , ROOM_LIST = 33 ,
ROOM_MESSAGE = 34 , ROOM_ERROR = 35 , HELLO = 1 , WELCOME = 2 ,
PING = 3 , PONG = 4 , INPUT = 10 , SNAPSHOT = 11 ,
EVENT = 12 , CREATE_ROOM = 20 , JOIN_ROOM = 21 , LEAVE_ROOM = 22 ,
LIST_ROOMS = 23 , MESSAGE = 24 , ROOM_CREATED = 30 , ROOM_JOINED = 31 ,
ROOM_LEFT = 32 , ROOM_LIST = 33 , ROOM_MESSAGE = 34 , ROOM_ERROR = 35
}
Functions
template<typename... Args>
void infof (const char *format, Args... args)
template<typename... Args>
void warnf (const char *format, Args... args)
template<typename... Args>
void errorf (const char *format, Args... args)
Typedef Documentation
udp
using RtypeServer::udp = boost::asio::ip::udp
Definition at line 16 of file UdpServer.cpp.
Enumeration Type Documentation
LogLevel
enum RtypeServer::LogLevel
Enumerator
DEBUG
INFO
WARNING
ERROR
Definition at line 16 of file Log.hpp.
MsgType [1/2]
enum class RtypeServer::MsgType : uint8_t strong
Enumerator
HELLO
WELCOME
PING
PONG
INPUT
SNAPSHOT
EVENT
CREATE_ROOM
JOIN_ROOM
LEAVE_ROOM
LIST_ROOMS
MESSAGE
ROOM_CREATED
ROOM_JOINED
ROOM_LEFT
ROOM_LIST
ROOM_MESSAGE
ROOM_ERROR
HELLO
WELCOME
PING
PONG
INPUT
SNAPSHOT
EVENT
CREATE_ROOM
JOIN_ROOM
LEAVE_ROOM
LIST_ROOMS
MESSAGE
ROOM_CREATED
ROOM_JOINED
ROOM_LEFT
ROOM_LIST
ROOM_MESSAGE
ROOM_ERROR
Definition at line 32 of file Client/include/net/Protocol.hpp.
MsgType [2/2]
enum class RtypeServer::MsgType : uint8_t strong
Enumerator
HELLO
WELCOME
PING
PONG
INPUT
SNAPSHOT
EVENT
CREATE_ROOM
JOIN_ROOM
LEAVE_ROOM
LIST_ROOMS
MESSAGE
ROOM_CREATED
ROOM_JOINED
ROOM_LEFT
ROOM_LIST
ROOM_MESSAGE
ROOM_ERROR
HELLO
WELCOME
PING
PONG
INPUT
SNAPSHOT
EVENT
CREATE_ROOM
JOIN_ROOM
LEAVE_ROOM
LIST_ROOMS
MESSAGE
ROOM_CREATED
ROOM_JOINED
ROOM_LEFT
ROOM_LIST
ROOM_MESSAGE
ROOM_ERROR
Definition at line 32 of file Server/src/net/Protocol.hpp.
Function Documentation
errorf()
template<typename... Args> void RtypeServer::errorf (const char * format, Args... args)
Definition at line 68 of file Log.hpp.
infof()
template<typename... Args> void RtypeServer::infof (const char * format, Args... args)
Definition at line 54 of file Log.hpp.
Referenced by RtypeServer::RoomManager::cleanup(), RtypeServer::RoomManager::createRoom(), RtypeServer::UdpServer::handle_create_room(), RtypeServer::UdpServer::handle_join_room(), RtypeServer::UdpServer::handle_leave_room(), RtypeServer::UdpServer::handle_list_rooms(), RtypeServer::UdpServer::handle_message(), RtypeServer::UdpServer::handle_receive(), RtypeServer::Room::join(), RtypeServer::Room::leave(), main(), RtypeServer::RoomManager::removeRoom(), RtypeServer::RoomManager::removeRoom(), RtypeServer::Room::Room(), RtypeServer::RoomManager::RoomManager(), RtypeServer::UdpServer::send_room_created(), RtypeServer::UdpServer::send_room_error(), RtypeServer::UdpServer::send_room_joined(), RtypeServer::UdpServer::send_room_left(), RtypeServer::UdpServer::send_room_list(), RtypeServer::UdpServer::send_welcome(), signalHandler(), RtypeServer::UdpServer::start_heartbeat(), and RtypeServer::UdpServer::UdpServer().
warnf()
template<typename... Args> void RtypeServer::warnf (const char * format, Args... args)
Definition at line 61 of file Log.hpp.
Referenced by RtypeServer::Room::broadcast(), RtypeServer::RoomManager::createRoom(), RtypeServer::UdpServer::handle_receive(), RtypeServer::Room::join(), RtypeServer::UdpServer::send_ping(), RtypeServer::UdpServer::send_pong(), RtypeServer::UdpServer::send_room_created(), RtypeServer::UdpServer::send_room_error(), RtypeServer::UdpServer::send_room_joined(), RtypeServer::UdpServer::send_room_left(), RtypeServer::UdpServer::send_room_list(), RtypeServer::UdpServer::send_welcome(), and RtypeServer::UdpServer::start_receive().