R-TYPE: main.cpp File Reference
main.cpp File Reference
#include <iostream>
#include <boost/asio.hpp>
#include <csignal>
#include <memory>
#include "net/UdpServer.hpp"
#include "util/Log.hpp"
Functions
void signalHandler (int signum)
int main (int argc, char *argv[])
Variables
static std::unique_ptr< boost::asio::io_context > g_io
static std::unique_ptr< RtypeServer::UdpServer > g_server
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 25 of file Server/src/main.cpp.
References g_io, g_server, RtypeServer::infof(), and signalHandler().
signalHandler()
void signalHandler (int signum)
Definition at line 18 of file Server/src/main.cpp.
References g_io, and RtypeServer::infof().
Referenced by main().
Variable Documentation
g_io
std::unique_ptr<boost::asio::io_context> g_io static
Definition at line 15 of file Server/src/main.cpp.
Referenced by main(), and signalHandler().
g_server
std::unique_ptr<RtypeServer::UdpServer> g_server static
Definition at line 16 of file Server/src/main.cpp.
Referenced by main().