name: Sync from School

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add school remote
        run: git remote add school git@github.com:EpitechPGE3-2025/G-CPP-500-BDX-5-1-rtype-1.git

      - name: Fetch school repo
        run: git fetch school

      - name: Push to origin
        run: git push origin refs/remotes/school/*:refs/heads/* --force
